// The menu. Order within a tier is the suggested cooking order.
//
// Authoring rules (enforced in curriculum.test.ts):
// - Every skill is taught by exactly one recipe.
// - Tier 5 ("the usual") teaches nothing new; it combines what came before.
// - A recipe may only require skills taught at its own tier or below.
// - A written recipe may only depend on written recipes.
// - Recipe text is original. Do not paste from books or sites.

import type { Recipe } from './types'

export const RECIPES: readonly Recipe[] = [
  // ───────────────────────── First course ─────────────────────────
  {
    id: 'chopped-salad',
    title: 'Chopped salad with lemon vinaigrette',
    tier: 1,
    track: 'foundations',
    blurb: 'No heat, no stress. Learn to hold a knife and to taste as you go.',
    teaches: ['knife-basics', 'seasoning'],
    requires: [],
    content: {
      servings: 2,
      activeMinutes: 15,
      totalMinutes: 15,
      equipment: ['Chef’s knife', 'Cutting board', 'Large bowl', 'Whisk or fork'],
      ingredients: [
        { ingredientId: 'tomato', qty: 2, prep: 'cut into bite-size chunks' },
        { ingredientId: 'cucumber', qty: 1, prep: 'halved lengthwise, sliced into half-moons' },
        { ingredientId: 'red-onion', qty: 0.25, prep: 'sliced as thin as you can' },
        { ingredientId: 'lemon', qty: 1, prep: 'juiced' },
        { ingredientId: 'olive-oil', qty: 2, prep: null },
        { ingredientId: 'kosher-salt', qty: 0.5, prep: null },
        { ingredientId: 'black-pepper', qty: 0.25, prep: null },
        { ingredientId: 'feta', qty: 2, prep: 'crumbled' },
      ],
      steps: [
        {
          text: 'Put a damp paper towel under your cutting board so it cannot slide.',
          why: 'A board that moves is how people get cut. Every cook does this first.',
          timerSeconds: null,
        },
        {
          text: 'Pinch the knife blade just in front of the handle with your thumb and forefinger. Curl the fingertips of your other hand into a claw, so your knuckles guide the blade.',
          why: 'The pinch gives you control. The claw keeps your fingertips behind the edge.',
          timerSeconds: null,
        },
        {
          text: 'Halve the cucumber lengthwise, lay the flat sides down, and slice into half-moons about as thick as a pencil.',
          why: 'Flat side down means nothing rolls. Always make a flat side first.',
          timerSeconds: null,
        },
        {
          text: 'Cut the tomatoes into wedges, then cut the wedges into bite-size chunks. Slice the quarter onion as thin as you can.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'In the large bowl, whisk 2 tablespoons of the lemon juice with the salt and pepper. Then whisk in the olive oil. Keep the rest of the lemon juice.',
          why: 'Salt dissolves in lemon juice but not in oil, so it goes in first.',
          timerSeconds: null,
        },
        {
          text: 'Add the vegetables and feta and toss. Now eat a piece.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'Adjust. If it tastes flat, add a pinch of salt. If it tastes dull or heavy, add a little more lemon. Toss and taste again until it tastes bright.',
          why: 'Taste, adjust, taste again is the most important habit in cooking. A recipe gets you close. Tasting gets you there.',
          timerSeconds: null,
        },
      ],
      delivery: { label: 'Side Greek salad', menuPriceCents: 950 },
      pairing: {
        wine: 'Sauvignon Blanc',
        principle: 'Match acid with acid',
        why: 'A lemony dressing makes soft wines taste flat. A wine with as much acid as the dish stays fresh next to it.',
      },
    },
  },
  {
    id: 'soft-scrambled-eggs',
    title: 'Soft scrambled eggs on toast',
    tier: 1,
    track: 'foundations',
    blurb: 'Three eggs and one burner. Learn that you control the heat, not the other way around.',
    teaches: ['heat-control'],
    requires: [],
    content: {
      servings: 1,
      activeMinutes: 10,
      totalMinutes: 10,
      equipment: ['Nonstick skillet, 8 to 10 inch', 'Silicone spatula', 'Small bowl', 'Fork', 'Toaster'],
      ingredients: [
        { ingredientId: 'eggs', qty: 3, prep: null },
        { ingredientId: 'butter', qty: 1.5, prep: null },
        { ingredientId: 'sandwich-bread', qty: 2, prep: null },
        { ingredientId: 'kosher-salt', qty: 0.25, prep: null },
        { ingredientId: 'black-pepper', qty: 0.125, prep: null },
      ],
      steps: [
        {
          text: 'Crack the eggs into the bowl, add the salt, and beat with the fork until no streaks of white remain.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'Start the toast.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'Put the skillet over medium-low heat and add 1 tablespoon of the butter. Wait until it melts and foams gently. If it sizzles loudly or starts to brown, lift the pan off the burner for 20 seconds.',
          why: 'Butter is your thermometer. A gentle foam means the pan is right for eggs.',
          timerSeconds: null,
        },
        {
          text: 'Pour in the eggs. Stir slowly and constantly with the spatula, scraping the bottom and sides, as soft curds form. This takes about 3 minutes.',
          why: 'If curds form faster than you can stir, lift the pan off the heat and keep stirring. Moving the pan is how you turn the heat down instantly.',
          timerSeconds: null,
        },
        {
          text: 'Take the pan off the heat while the eggs still look slightly wet and glossy.',
          why: 'Eggs keep cooking from their own heat. If they look done in the pan, they will be overdone on the plate.',
          timerSeconds: null,
        },
        {
          text: 'Butter the toast with the remaining butter, pile the eggs on top, and finish with the pepper.',
          why: null,
          timerSeconds: null,
        },
      ],
      delivery: { label: 'Eggs and toast breakfast plate', menuPriceCents: 1100 },
      pairing: {
        wine: 'Cava or another dry sparkling wine',
        principle: 'Bubbles cut richness',
        why: 'Buttery eggs coat your mouth. Bubbles and acid clear it, which is why brunch runs on sparkling wine.',
      },
    },
  },
  {
    id: 'aglio-e-olio',
    title: 'Spaghetti aglio e olio',
    tier: 1,
    track: 'foundations',
    blurb: 'Garlic, oil and pasta. Learn to boil pasta properly and to have everything ready before the heat goes on.',
    teaches: ['boiling-pasta', 'mise-en-place'],
    requires: ['knife-basics', 'heat-control'],
    content: {
      servings: 2,
      activeMinutes: 20,
      totalMinutes: 30,
      equipment: ['Large pot with lid', 'Large skillet, 12 inch', 'Tongs', 'Mug', 'Colander', 'Grater'],
      ingredients: [
        { ingredientId: 'spaghetti', qty: 8, prep: null },
        { ingredientId: 'garlic', qty: 6, prep: 'thinly sliced' },
        { ingredientId: 'olive-oil', qty: 4, prep: null },
        { ingredientId: 'red-pepper-flakes', qty: 0.5, prep: null },
        { ingredientId: 'parsley', qty: 0.25, prep: 'leaves chopped' },
        { ingredientId: 'parmesan', qty: 1, prep: 'finely grated' },
        { ingredientId: 'kosher-salt', qty: 6, prep: 'for the pasta water' },
      ],
      steps: [
        {
          text: 'Before any heat: slice the garlic thin, chop the parsley, grate the parmesan, and measure the oil and pepper flakes. Set it all next to the stove.',
          why: 'This is mise en place. Once the garlic is in the pan there is no time to chop anything.',
          timerSeconds: null,
        },
        {
          text: 'Fill the pot with about 4 quarts of water, cover, and bring to a full rolling boil over high heat. Add the salt: 2 tablespoons, which is the 6 teaspoons in the list.',
          why: 'The water is your only chance to season the pasta itself. It should taste like mild seawater.',
          timerSeconds: null,
        },
        {
          text: 'Add the spaghetti and stir for the first 30 seconds so it does not stick. Cook it 2 minutes less than the box says. The timer is set for a 10-minute box.',
          why: 'The pasta finishes cooking in the skillet, where it soaks up sauce instead of water.',
          timerSeconds: 480,
        },
        {
          text: 'While the pasta boils, put the oil and garlic in the cold skillet and turn the heat to medium-low. Stir now and then until the garlic is pale gold, 3 to 5 minutes.',
          why: 'Starting cold lets the garlic flavor the oil slowly. Brown garlic is bitter. If it goes dark, wipe out the pan and redo this step. It is 50 cents of garlic.',
          timerSeconds: null,
        },
        {
          text: 'Stir in the pepper flakes and turn the heat off.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'Before you drain, dip the mug into the pot and fill it with pasta water. Then drain the spaghetti.',
          why: 'That cloudy water is full of starch. It is what turns oil into sauce instead of grease.',
          timerSeconds: null,
        },
        {
          text: 'Add the spaghetti and half the mug of pasta water to the skillet. Turn the heat to medium and toss constantly with the tongs until the liquid thickens and clings to the pasta, 1 to 2 minutes. Add a splash more water if it looks dry.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'Off the heat, toss in the parsley and parmesan. Taste, and add a pinch of salt if it needs it.',
          why: null,
          timerSeconds: null,
        },
      ],
      delivery: { label: 'Spaghetti aglio e olio', menuPriceCents: 1600 },
      pairing: {
        wine: 'Vermentino or Pinot Grigio',
        principle: 'What grows together goes together',
        why: 'A simple Italian dish built on oil and garlic wants a crisp, unoaked Italian white that will not bury it.',
      },
    },
  },
  {
    id: 'grilled-cheese',
    title: 'Grilled cheese',
    tier: 1,
    track: 'foundations',
    blurb: 'The first sandwich on the way to the burger. Learn that browning takes patience and moderate heat.',
    teaches: ['griddling'],
    requires: ['heat-control'],
    content: {
      servings: 1,
      activeMinutes: 10,
      totalMinutes: 12,
      equipment: ['Skillet, nonstick or cast iron', 'Lid or plate that covers the skillet', 'Spatula', 'Butter knife'],
      ingredients: [
        { ingredientId: 'sandwich-bread', qty: 2, prep: null },
        { ingredientId: 'butter', qty: 1, prep: 'softened' },
        { ingredientId: 'cheddar', qty: 2, prep: 'sliced thin or grated' },
      ],
      steps: [
        {
          text: 'Spread the butter over one side of each slice of bread, all the way to the edges.',
          why: 'Bare spots stay pale or burn. Edge-to-edge fat means edge-to-edge browning.',
          timerSeconds: null,
        },
        {
          text: 'Put one slice butter-side down in the cold skillet. Cover it with the cheese and top with the second slice, butter-side up.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'Turn the heat to medium-low and cook until the bottom is deep golden brown. Lift a corner to check.',
          why: 'High heat burns the bread before the cheese melts. Browning is slow, and that is the whole lesson here.',
          timerSeconds: 240,
        },
        {
          text: 'Flip. Cover the skillet and cook until the second side is golden and the cheese is fully melted.',
          why: 'The lid traps heat so the cheese melts from above.',
          timerSeconds: 180,
        },
        {
          text: 'Rest the sandwich on the cutting board, then cut it in half.',
          why: 'A minute lets the cheese set enough that it does not all run out.',
          timerSeconds: 60,
        },
      ],
      delivery: { label: 'Grilled cheese sandwich', menuPriceCents: 1000 },
      pairing: {
        wine: 'Beaujolais (Gamay)',
        principle: 'High acid and low tannin for rich, salty food',
        why: 'Melted cheese is fat and salt. A light, juicy red refreshes. A heavy, tannic red would turn harsh against it.',
      },
    },
  },
  {
    id: 'fried-egg-rice-bowl',
    title: 'Rice bowl with a crispy fried egg',
    tier: 1,
    track: 'foundations',
    blurb: 'The first step toward fried rice and curry. Learn to make a pot of rice you can count on.',
    teaches: ['steaming-rice'],
    requires: ['knife-basics', 'heat-control'],
    content: {
      servings: 2,
      activeMinutes: 15,
      totalMinutes: 35,
      equipment: ['Small saucepan with a tight lid', 'Fine-mesh strainer', 'Nonstick skillet', 'Spatula', 'Fork'],
      ingredients: [
        { ingredientId: 'jasmine-rice', qty: 1, prep: null },
        { ingredientId: 'eggs', qty: 2, prep: null },
        { ingredientId: 'scallion', qty: 2, prep: 'thinly sliced' },
        { ingredientId: 'neutral-oil', qty: 1, prep: null },
        { ingredientId: 'soy-sauce', qty: 1, prep: null },
        { ingredientId: 'sesame-oil', qty: 1, prep: null },
      ],
      steps: [
        {
          text: 'Rinse the rice in the strainer under cold water, swishing it with your hand, until the water runs mostly clear.',
          why: 'Rinsing washes off loose starch, which is what makes rice gummy.',
          timerSeconds: null,
        },
        {
          text: 'Put the rice and 1¼ cups of water in the saucepan. Bring to a boil over high heat.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'As soon as it boils, stir once, put the lid on, and turn the heat to its lowest setting. Do not lift the lid.',
          why: 'Rice cooks in steam. Every peek lets the steam out.',
          timerSeconds: 900,
        },
        {
          text: 'Turn the heat off and leave the lid on. While the rice rests, slice the scallions.',
          why: 'The rest lets moisture even out, so the bottom is not wet and the top is not dry.',
          timerSeconds: 600,
        },
        {
          text: 'Heat the neutral oil in the skillet over medium-high until it shimmers. Crack in the eggs and fry without moving them until the whites are set and the edges are brown and crisp, 2 to 3 minutes.',
          why: 'Shimmering oil means the pan is hot enough to crisp the edges. It will spit a little, and that is normal. This is the other end of the dial from scrambled eggs.',
          timerSeconds: null,
        },
        {
          text: 'Fluff the rice with the fork and divide it between two bowls. Top each with an egg, half the soy sauce, half the sesame oil, and the scallions.',
          why: null,
          timerSeconds: null,
        },
      ],
      delivery: { label: 'Rice bowl with egg', menuPriceCents: 1300 },
      pairing: {
        wine: 'Off-dry Riesling',
        principle: 'A little sweetness for salty, savory food',
        why: 'Soy sauce is salt and umami, which make bone-dry wines taste bitter. A touch of sweetness with high acid balances it.',
      },
    },
  },
  {
    id: 'sheet-pan-sausage',
    title: 'Sheet-pan sausage and vegetables',
    tier: 1,
    track: 'foundations',
    blurb: 'A full dinner on one pan. Learn how a hot oven browns food, and why crowding ruins it.',
    teaches: ['roasting'],
    requires: ['knife-basics', 'seasoning'],
    content: {
      servings: 3,
      activeMinutes: 15,
      totalMinutes: 50,
      equipment: ['Rimmed sheet pan', 'Chef’s knife', 'Cutting board', 'Large bowl', 'Spatula or tongs'],
      ingredients: [
        { ingredientId: 'kielbasa', qty: 1, prep: 'sliced into ½-inch coins' },
        { ingredientId: 'baby-potatoes', qty: 1, prep: 'halved' },
        { ingredientId: 'broccoli', qty: 1, prep: 'cut into florets' },
        { ingredientId: 'bell-pepper', qty: 1, prep: 'cut into 1-inch pieces' },
        { ingredientId: 'red-onion', qty: 1, prep: 'cut into wedges' },
        { ingredientId: 'olive-oil', qty: 2, prep: null },
        { ingredientId: 'kosher-salt', qty: 1, prep: null },
        { ingredientId: 'black-pepper', qty: 0.5, prep: null },
      ],
      steps: [
        {
          text: 'Put a rack in the middle of the oven and heat it to 425°F. Wait until it has fully preheated.',
          why: 'Roasting needs a hot oven from the first minute. Food that goes into a warming oven steams instead of browning.',
          timerSeconds: null,
        },
        {
          text: 'Halve the potatoes. Toss them on the sheet pan with 1 tablespoon of the oil and half the salt, then turn each one cut-side down.',
          why: 'The cut side touching hot metal is where the best browning happens.',
          timerSeconds: null,
        },
        {
          text: 'Roast the potatoes on their own.',
          why: 'Potatoes take the longest, so they get a head start. Staggering is how everything finishes together.',
          timerSeconds: 900,
        },
        {
          text: 'While they roast, cut the broccoli, pepper and onion into pieces about the size of the potato halves, and slice the sausage. Toss it all in the bowl with the remaining oil, the remaining salt and the pepper.',
          why: 'Pieces the same size cook at the same rate.',
          timerSeconds: null,
        },
        {
          text: 'Add everything to the pan and spread it into a single layer with a little space between pieces.',
          why: 'Crowded food traps steam and turns soft. If it does not fit in one layer, use a second pan.',
          timerSeconds: null,
        },
        {
          text: 'Roast, stirring once halfway, until a fork slides easily into a potato and the edges of the vegetables are browned.',
          why: 'The sausage is already cooked, so you are only browning it. Judging raw meat comes later, with a thermometer.',
          timerSeconds: 1200,
        },
        {
          text: 'Taste a potato and a piece of broccoli. Add a pinch of salt if they need it.',
          why: null,
          timerSeconds: null,
        },
      ],
      delivery: { label: 'Sausage and roasted vegetable plate', menuPriceCents: 1500 },
      pairing: {
        wine: 'Côtes du Rhône',
        principle: 'Match weight with weight',
        why: 'Smoky sausage and roasted vegetables are medium-heavy food. A medium-bodied, fruity red stands up to them without taking over.',
      },
    },
  },

  // ───────────────────────── Second course ─────────────────────────
  {
    id: 'marinara-pasta',
    title: 'Pasta with quick marinara',
    tier: 2,
    track: 'pizza-pasta',
    blurb: 'Your first real sauce. Later it becomes your pizza sauce.',
    teaches: ['sweating-aromatics', 'simmering'],
    requires: ['boiling-pasta', 'knife-basics'],
    content: null,
  },
  {
    id: 'pasta-al-limone',
    title: 'Pasta al limone',
    tier: 2,
    track: 'pizza-pasta',
    blurb: 'Butter, lemon and pasta water become a sauce with nothing else holding them together.',
    teaches: ['pan-emulsion'],
    requires: ['boiling-pasta', 'mise-en-place'],
    content: null,
  },
  {
    id: 'seared-chicken-thighs',
    title: 'Seared chicken thighs with roasted broccoli',
    tier: 2,
    track: 'foundations',
    blurb: 'Your first raw meat, with a thermometer to take the guessing out of it.',
    teaches: ['searing', 'doneness'],
    requires: ['heat-control', 'seasoning', 'roasting'],
    content: null,
  },
  {
    id: 'egg-fried-rice',
    title: 'Egg fried rice',
    tier: 2,
    track: 'wok-curry',
    blurb: 'Yesterday’s rice, a very hot pan, and no time to chop once you start.',
    teaches: ['stir-frying'],
    requires: ['steaming-rice', 'mise-en-place', 'knife-basics'],
    content: null,
  },
  {
    id: 'onion-melt',
    title: 'Caramelized onion melt',
    tier: 2,
    track: 'burgers-sandwiches',
    blurb: 'Grilled cheese with onions you cooked for forty patient minutes.',
    teaches: ['caramelizing'],
    requires: ['griddling', 'knife-basics'],
    content: null,
  },
  {
    id: 'red-lentil-dal',
    title: 'Red lentil dal with rice',
    tier: 2,
    track: 'wok-curry',
    blurb: 'A pot of lentils finished with spices sizzled in hot oil.',
    teaches: ['blooming-spices'],
    requires: ['steaming-rice', 'sweating-aromatics'],
    content: null,
  },

  // ───────────────────────── Third course ─────────────────────────
  {
    id: 'chicken-pan-sauce',
    title: 'Chicken with lemon pan sauce',
    tier: 3,
    track: 'foundations',
    blurb: 'The brown bits stuck to the pan are the sauce. Learn to get them back.',
    teaches: ['pan-sauce'],
    requires: ['searing', 'doneness'],
    content: null,
  },
  {
    id: 'smash-cheeseburger',
    title: 'Single smash cheeseburger',
    tier: 3,
    track: 'burgers-sandwiches',
    blurb: 'One patty, one slice of cheese, one toasted bun. All of it is about the crust.',
    teaches: ['smash-crust'],
    requires: ['searing', 'griddling'],
    content: null,
  },
  {
    id: 'weeknight-meat-sauce',
    title: 'Weeknight meat sauce',
    tier: 3,
    track: 'pizza-pasta',
    blurb: 'Marinara with browned beef. The short version of the ragù you are working toward.',
    teaches: ['browning-meat'],
    requires: ['simmering', 'sweating-aromatics', 'boiling-pasta'],
    content: null,
  },
  {
    id: 'chicken-broccoli-stir-fry',
    title: 'Chicken and broccoli stir-fry',
    tier: 3,
    track: 'wok-curry',
    blurb: 'A takeout standard, and the sauce method behind most of the others.',
    teaches: ['stir-fry-sauce'],
    requires: ['stir-frying', 'steaming-rice', 'doneness'],
    content: null,
  },
  {
    id: 'chana-masala',
    title: 'Chana masala',
    tier: 3,
    track: 'wok-curry',
    blurb: 'Chickpeas in the onion-tomato base that most North Indian curries start from.',
    teaches: ['masala-base'],
    requires: ['blooming-spices', 'simmering'],
    content: null,
  },
  {
    id: 'oven-fries-aioli',
    title: 'Oven fries with garlic aioli',
    tier: 3,
    track: 'burgers-sandwiches',
    blurb: 'The side for every burger, with a sauce you whisk from an egg yolk and oil.',
    teaches: ['emulsions'],
    requires: ['roasting', 'knife-basics'],
    content: null,
  },

  // ───────────────────────── Fourth course ─────────────────────────
  {
    id: 'pan-pizza',
    title: 'Cast-iron pan pizza',
    tier: 4,
    track: 'pizza-pasta',
    blurb: 'A forgiving dough that proofs in the same pan it bakes in.',
    teaches: ['yeasted-dough'],
    requires: ['simmering', 'roasting'],
    content: null,
  },
  {
    id: 'carbonara',
    title: 'Spaghetti carbonara',
    tier: 4,
    track: 'pizza-pasta',
    blurb: 'Eggs, cheese and pork fat, held just short of scrambling.',
    teaches: ['tempering-eggs'],
    requires: ['pan-emulsion', 'mise-en-place'],
    content: null,
  },
  {
    id: 'chicken-cutlets',
    title: 'Crispy chicken cutlets',
    tier: 4,
    track: 'burgers-sandwiches',
    blurb: 'Pounded thin, breaded, and fried in half an inch of oil.',
    teaches: ['breading-frying'],
    requires: ['searing', 'doneness'],
    content: null,
  },
  {
    id: 'thai-green-curry',
    title: 'Thai green curry with chicken',
    tier: 4,
    track: 'wok-curry',
    blurb: 'Store-bought paste, coconut milk, and the last-minute balancing that makes it taste like the restaurant’s.',
    teaches: ['curry-balance'],
    requires: ['stir-frying', 'steaming-rice', 'seasoning', 'doneness'],
    content: null,
  },
  {
    id: 'beef-and-broccoli',
    title: 'Beef and broccoli',
    tier: 4,
    track: 'wok-curry',
    blurb: 'The reason takeout beef is so tender, and how to do it at home.',
    teaches: ['velveting'],
    requires: ['stir-fry-sauce'],
    content: null,
  },
  {
    id: 'chicken-tikka',
    title: 'Broiled chicken tikka',
    tier: 4,
    track: 'wok-curry',
    blurb: 'Yogurt-marinated chicken charred under the broiler. Half of a tikka masala.',
    teaches: ['marinating-broiling'],
    requires: ['blooming-spices', 'doneness'],
    content: null,
  },

  // ───────────────────────── The usual ─────────────────────────
  {
    id: 'double-smash-burger',
    title: 'Double smash burger with oven fries',
    tier: 5,
    track: 'burgers-sandwiches',
    blurb: 'Two crusted patties, caramelized onions, your own burger sauce, fries on the side.',
    teaches: [],
    requires: ['smash-crust', 'caramelizing', 'emulsions'],
    content: null,
  },
  {
    id: 'crispy-chicken-sandwich',
    title: 'Crispy chicken sandwich',
    tier: 5,
    track: 'burgers-sandwiches',
    blurb: 'A fried cutlet on a toasted bun with pickles and spicy mayo.',
    teaches: [],
    requires: ['breading-frying', 'emulsions', 'griddling'],
    content: null,
  },
  {
    id: 'margherita-pizza',
    title: 'Margherita pizza',
    tier: 5,
    track: 'pizza-pasta',
    blurb: 'Hand-stretched dough, your own sauce, and the hottest oven you have.',
    teaches: [],
    requires: ['yeasted-dough', 'simmering'],
    content: null,
  },
  {
    id: 'ragu-bolognese',
    title: 'Tagliatelle with ragù bolognese',
    tier: 5,
    track: 'pizza-pasta',
    blurb: 'Three hours on the stove, most of them hands-off. The pasta order that travels worst and cooks best.',
    teaches: [],
    requires: ['browning-meat', 'pan-sauce', 'pan-emulsion'],
    content: null,
  },
  {
    id: 'pad-thai',
    title: 'Pad thai',
    tier: 5,
    track: 'wok-curry',
    blurb: 'Rice noodles, a sweet-sour-salty sauce, and four minutes of fast cooking.',
    teaches: [],
    requires: ['stir-fry-sauce', 'curry-balance', 'mise-en-place'],
    content: null,
  },
  {
    id: 'general-tsos-chicken',
    title: 'General Tso’s chicken',
    tier: 5,
    track: 'wok-curry',
    blurb: 'Crisp fried chicken in a glossy, sticky sauce, over your own rice.',
    teaches: [],
    requires: ['breading-frying', 'velveting', 'stir-fry-sauce', 'steaming-rice'],
    content: null,
  },
  {
    id: 'chicken-tikka-masala',
    title: 'Chicken tikka masala',
    tier: 5,
    track: 'wok-curry',
    blurb: 'Broiled tikka folded into a creamy masala. Two things you already know, combined.',
    teaches: [],
    requires: ['masala-base', 'marinating-broiling', 'steaming-rice'],
    content: null,
  },
]

export function recipeById(id: string): Recipe {
  const recipe = RECIPES.find((r) => r.id === id)
  if (!recipe) throw new Error(`Unknown recipe id: ${id}`)
  return recipe
}
