// The menu. Order within a tier is the suggested cooking order.
//
// Authoring rules (enforced in curriculum.test.ts):
// - Every skill is taught by exactly one recipe.
// - Tier 5 ("the usual") teaches nothing new; it combines what came before.
// - A recipe may only require skills taught at its own tier or below.
// - A written recipe may only depend on written recipes.
// - Recipe text is original. Do not paste from books or sites.

import type { Recipe } from './types'

export const RECIPES: readonly Recipe[] = [
  // ───────────────────────── First course ─────────────────────────
  {
    id: 'chopped-salad',
    title: 'Chopped salad with lemon vinaigrette',
    tier: 1,
    track: 'foundations',
    blurb: 'No heat, no stress. Learn to hold a knife and to taste as you go.',
    teaches: ['knife-basics', 'seasoning'],
    requires: [],
    content: {
      servings: 2,
      activeMinutes: 15,
      totalMinutes: 15,
      equipment: ['Chef’s knife', 'Cutting board', 'Large bowl', 'Whisk or fork'],
      ingredients: [
        { ingredientId: 'tomato', qty: 2, prep: 'cut into bite-size chunks' },
        { ingredientId: 'cucumber', qty: 1, prep: 'halved lengthwise, sliced into half-moons' },
        { ingredientId: 'red-onion', qty: 0.25, prep: 'sliced as thin as you can' },
        { ingredientId: 'lemon', qty: 1, prep: 'juiced' },
        { ingredientId: 'olive-oil', qty: 2, prep: null },
        { ingredientId: 'kosher-salt', qty: 0.5, prep: null },
        { ingredientId: 'black-pepper', qty: 0.25, prep: null },
        { ingredientId: 'feta', qty: 2, prep: 'crumbled' },
      ],
      steps: [
        {
          text: 'Put a damp paper towel under your cutting board so it cannot slide.',
          why: 'A board that moves is how people get cut. Every cook does this first.',
          timerSeconds: null,
        },
        {
          text: 'Pinch the knife blade just in front of the handle with your thumb and forefinger. Curl the fingertips of your other hand into a claw, so your knuckles guide the blade.',
          why: 'The pinch gives you control. The claw keeps your fingertips behind the edge.',
          timerSeconds: null,
        },
        {
          text: 'Halve the cucumber lengthwise, lay the flat sides down, and slice into half-moons about as thick as a pencil.',
          why: 'Flat side down means nothing rolls. Always make a flat side first.',
          timerSeconds: null,
        },
        {
          text: 'Cut the tomatoes into wedges, then cut the wedges into bite-size chunks. Slice the quarter onion as thin as you can.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'In the large bowl, whisk 2 tablespoons of the lemon juice with the salt and pepper. Then whisk in the olive oil. Keep the rest of the lemon juice.',
          why: 'Salt dissolves in lemon juice but not in oil, so it goes in first.',
          timerSeconds: null,
        },
        {
          text: 'Add the vegetables and feta and toss. Now eat a piece.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'Adjust. If it tastes flat, add a pinch of salt. If it tastes dull or heavy, add a little more lemon. Toss and taste again until it tastes bright.',
          why: 'Taste, adjust, taste again is the most important habit in cooking. A recipe gets you close. Tasting gets you there.',
          timerSeconds: null,
        },
      ],
      delivery: { label: 'Side Greek salad', menuPriceCents: 950 },
      pairing: {
        wine: 'Sauvignon Blanc',
        principle: 'Match acid with acid',
        why: 'A lemony dressing makes soft wines taste flat. A wine with as much acid as the dish stays fresh next to it.',
      },
    },
  },
  {
    id: 'soft-scrambled-eggs',
    title: 'Soft scrambled eggs on toast',
    tier: 1,
    track: 'foundations',
    blurb: 'Three eggs and one burner. Learn that you control the heat, not the other way around.',
    teaches: ['heat-control'],
    requires: [],
    content: {
      servings: 1,
      activeMinutes: 10,
      totalMinutes: 10,
      equipment: ['Nonstick skillet, 8 to 10 inch', 'Silicone spatula', 'Small bowl', 'Fork', 'Toaster'],
      ingredients: [
        { ingredientId: 'eggs', qty: 3, prep: null },
        { ingredientId: 'butter', qty: 1.5, prep: null },
        { ingredientId: 'sandwich-bread', qty: 2, prep: null },
        { ingredientId: 'kosher-salt', qty: 0.25, prep: null },
        { ingredientId: 'black-pepper', qty: 0.125, prep: null },
      ],
      steps: [
        {
          text: 'Crack the eggs into the bowl, add the salt, and beat with the fork until no streaks of white remain.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'Start the toast.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'Put the skillet over medium-low heat and add 1 tablespoon of the butter. Wait until it melts and foams gently. If it sizzles loudly or starts to brown, lift the pan off the burner for 20 seconds.',
          why: 'Butter is your thermometer. A gentle foam means the pan is right for eggs.',
          timerSeconds: null,
        },
        {
          text: 'Pour in the eggs. Stir slowly and constantly with the spatula, scraping the bottom and sides, as soft curds form. This takes about 3 minutes.',
          why: 'If curds form faster than you can stir, lift the pan off the heat and keep stirring. Moving the pan is how you turn the heat down instantly.',
          timerSeconds: null,
        },
        {
          text: 'Take the pan off the heat while the eggs still look slightly wet and glossy.',
          why: 'Eggs keep cooking from their own heat. If they look done in the pan, they will be overdone on the plate.',
          timerSeconds: null,
        },
        {
          text: 'Butter the toast with the remaining butter, pile the eggs on top, and finish with the pepper.',
          why: null,
          timerSeconds: null,
        },
      ],
      delivery: { label: 'Eggs and toast breakfast plate', menuPriceCents: 1100 },
      pairing: {
        wine: 'Cava or another dry sparkling wine',
        principle: 'Bubbles cut richness',
        why: 'Buttery eggs coat your mouth. Bubbles and acid clear it, which is why brunch runs on sparkling wine.',
      },
    },
  },
  {
    id: 'aglio-e-olio',
    title: 'Spaghetti aglio e olio',
    tier: 1,
    track: 'foundations',
    blurb: 'Garlic, oil and pasta. Learn to boil pasta properly and to have everything ready before the heat goes on.',
    teaches: ['boiling-pasta', 'mise-en-place'],
    requires: ['knife-basics', 'heat-control'],
    content: {
      servings: 2,
      activeMinutes: 20,
      totalMinutes: 30,
      equipment: ['Large pot with lid', 'Large skillet, 12 inch', 'Tongs', 'Mug', 'Colander', 'Grater'],
      ingredients: [
        { ingredientId: 'spaghetti', qty: 8, prep: null },
        { ingredientId: 'garlic', qty: 6, prep: 'thinly sliced' },
        { ingredientId: 'olive-oil', qty: 4, prep: null },
        { ingredientId: 'red-pepper-flakes', qty: 0.5, prep: null },
        { ingredientId: 'parsley', qty: 0.25, prep: 'leaves chopped' },
        { ingredientId: 'parmesan', qty: 1, prep: 'finely grated' },
        { ingredientId: 'kosher-salt', qty: 6, prep: 'for the pasta water' },
      ],
      steps: [
        {
          text: 'Before any heat: slice the garlic thin, chop the parsley, grate the parmesan, and measure the oil and pepper flakes. Set it all next to the stove.',
          why: 'This is mise en place. Once the garlic is in the pan there is no time to chop anything.',
          timerSeconds: null,
        },
        {
          text: 'Fill the pot with about 4 quarts of water, cover, and bring to a full rolling boil over high heat. Add the salt: 2 tablespoons, which is the 6 teaspoons in the list.',
          why: 'The water is your only chance to season the pasta itself. It should taste like mild seawater.',
          timerSeconds: null,
        },
        {
          text: 'Add the spaghetti and stir for the first 30 seconds so it does not stick. Cook it 2 minutes less than the box says. The timer is set for a 10-minute box.',
          why: 'The pasta finishes cooking in the skillet, where it soaks up sauce instead of water.',
          timerSeconds: 480,
        },
        {
          text: 'While the pasta boils, put the oil and garlic in the cold skillet and turn the heat to medium-low. Stir now and then until the garlic is pale gold, 3 to 5 minutes.',
          why: 'Starting cold lets the garlic flavor the oil slowly. Brown garlic is bitter. If it goes dark, wipe out the pan and redo this step. It is 50 cents of garlic.',
          timerSeconds: null,
        },
        {
          text: 'Stir in the pepper flakes and turn the heat off.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'Before you drain, dip the mug into the pot and fill it with pasta water. Then drain the spaghetti.',
          why: 'That cloudy water is full of starch. It is what turns oil into sauce instead of grease.',
          timerSeconds: null,
        },
        {
          text: 'Add the spaghetti and half the mug of pasta water to the skillet. Turn the heat to medium and toss constantly with the tongs until the liquid thickens and clings to the pasta, 1 to 2 minutes. Add a splash more water if it looks dry.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'Off the heat, toss in the parsley and parmesan. Taste, and add a pinch of salt if it needs it.',
          why: null,
          timerSeconds: null,
        },
      ],
      delivery: { label: 'Spaghetti aglio e olio', menuPriceCents: 1600 },
      pairing: {
        wine: 'Vermentino or Pinot Grigio',
        principle: 'What grows together goes together',
        why: 'A simple Italian dish built on oil and garlic wants a crisp, unoaked Italian white that will not bury it.',
      },
    },
  },
  {
    id: 'grilled-cheese',
    title: 'Grilled cheese',
    tier: 1,
    track: 'foundations',
    blurb: 'The first sandwich on the way to the burger. Learn that browning takes patience and moderate heat.',
    teaches: ['griddling'],
    requires: ['heat-control'],
    content: {
      servings: 1,
      activeMinutes: 10,
      totalMinutes: 12,
      equipment: ['Skillet, nonstick or cast iron', 'Lid or plate that covers the skillet', 'Spatula', 'Butter knife'],
      ingredients: [
        { ingredientId: 'sandwich-bread', qty: 2, prep: null },
        { ingredientId: 'butter', qty: 1, prep: 'softened' },
        { ingredientId: 'cheddar', qty: 2, prep: 'sliced thin or grated' },
      ],
      steps: [
        {
          text: 'Spread the butter over one side of each slice of bread, all the way to the edges.',
          why: 'Bare spots stay pale or burn. Edge-to-edge fat means edge-to-edge browning.',
          timerSeconds: null,
        },
        {
          text: 'Put one slice butter-side down in the cold skillet. Cover it with the cheese and top with the second slice, butter-side up.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'Turn the heat to medium-low and cook until the bottom is deep golden brown. Lift a corner to check.',
          why: 'High heat burns the bread before the cheese melts. Browning is slow, and that is the whole lesson here.',
          timerSeconds: 240,
        },
        {
          text: 'Flip. Cover the skillet and cook until the second side is golden and the cheese is fully melted.',
          why: 'The lid traps heat so the cheese melts from above.',
          timerSeconds: 180,
        },
        {
          text: 'Rest the sandwich on the cutting board, then cut it in half.',
          why: 'A minute lets the cheese set enough that it does not all run out.',
          timerSeconds: 60,
        },
      ],
      delivery: { label: 'Grilled cheese sandwich', menuPriceCents: 1000 },
      pairing: {
        wine: 'Beaujolais (Gamay)',
        principle: 'High acid and low tannin for rich, salty food',
        why: 'Melted cheese is fat and salt. A light, juicy red refreshes. A heavy, tannic red would turn harsh against it.',
      },
    },
  },
  {
    id: 'fried-egg-rice-bowl',
    title: 'Rice bowl with a crispy fried egg',
    tier: 1,
    track: 'foundations',
    blurb: 'The first step toward fried rice and curry. Learn to make a pot of rice you can count on.',
    teaches: ['steaming-rice'],
    requires: ['knife-basics', 'heat-control'],
    content: {
      servings: 2,
      activeMinutes: 15,
      totalMinutes: 35,
      equipment: ['Small saucepan with a tight lid', 'Fine-mesh strainer', 'Nonstick skillet', 'Spatula', 'Fork'],
      ingredients: [
        { ingredientId: 'jasmine-rice', qty: 1, prep: null },
        { ingredientId: 'eggs', qty: 2, prep: null },
        { ingredientId: 'scallion', qty: 2, prep: 'thinly sliced' },
        { ingredientId: 'neutral-oil', qty: 1, prep: null },
        { ingredientId: 'soy-sauce', qty: 1, prep: null },
        { ingredientId: 'sesame-oil', qty: 1, prep: null },
      ],
      steps: [
        {
          text: 'Rinse the rice in the strainer under cold water, swishing it with your hand, until the water runs mostly clear.',
          why: 'Rinsing washes off loose starch, which is what makes rice gummy.',
          timerSeconds: null,
        },
        {
          text: 'Put the rice and 1¼ cups of water in the saucepan. Bring to a boil over high heat.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'As soon as it boils, stir once, put the lid on, and turn the heat to its lowest setting. Do not lift the lid.',
          why: 'Rice cooks in steam. Every peek lets the steam out.',
          timerSeconds: 900,
        },
        {
          text: 'Turn the heat off and leave the lid on. While the rice rests, slice the scallions.',
          why: 'The rest lets moisture even out, so the bottom is not wet and the top is not dry.',
          timerSeconds: 600,
        },
        {
          text: 'Heat the neutral oil in the skillet over medium-high until it shimmers. Crack in the eggs and fry without moving them until the whites are set and the edges are brown and crisp, 2 to 3 minutes.',
          why: 'Shimmering oil means the pan is hot enough to crisp the edges. It will spit a little, and that is normal. This is the other end of the dial from scrambled eggs.',
          timerSeconds: null,
        },
        {
          text: 'Fluff the rice with the fork and divide it between two bowls. Top each with an egg, half the soy sauce, half the sesame oil, and the scallions.',
          why: null,
          timerSeconds: null,
        },
      ],
      delivery: { label: 'Rice bowl with egg', menuPriceCents: 1300 },
      pairing: {
        wine: 'Off-dry Riesling',
        principle: 'A little sweetness for salty, savory food',
        why: 'Soy sauce is salt and umami, which make bone-dry wines taste bitter. A touch of sweetness with high acid balances it.',
      },
    },
  },
  {
    id: 'sheet-pan-sausage',
    title: 'Sheet-pan sausage and vegetables',
    tier: 1,
    track: 'foundations',
    blurb: 'A full dinner on one pan. Learn how a hot oven browns food, and why crowding ruins it.',
    teaches: ['roasting'],
    requires: ['knife-basics', 'seasoning'],
    content: {
      servings: 3,
      activeMinutes: 15,
      totalMinutes: 50,
      equipment: ['Rimmed sheet pan', 'Chef’s knife', 'Cutting board', 'Large bowl', 'Spatula or tongs'],
      ingredients: [
        { ingredientId: 'kielbasa', qty: 1, prep: 'sliced into ½-inch coins' },
        { ingredientId: 'baby-potatoes', qty: 1, prep: 'halved' },
        { ingredientId: 'broccoli', qty: 1, prep: 'cut into florets' },
        { ingredientId: 'bell-pepper', qty: 1, prep: 'cut into 1-inch pieces' },
        { ingredientId: 'red-onion', qty: 1, prep: 'cut into wedges' },
        { ingredientId: 'olive-oil', qty: 2, prep: null },
        { ingredientId: 'kosher-salt', qty: 1, prep: null },
        { ingredientId: 'black-pepper', qty: 0.5, prep: null },
      ],
      steps: [
        {
          text: 'Put a rack in the middle of the oven and heat it to 425°F. Wait until it has fully preheated.',
          why: 'Roasting needs a hot oven from the first minute. Food that goes into a warming oven steams instead of browning.',
          timerSeconds: null,
        },
        {
          text: 'Halve the potatoes. Toss them on the sheet pan with 1 tablespoon of the oil and half the salt, then turn each one cut-side down.',
          why: 'The cut side touching hot metal is where the best browning happens.',
          timerSeconds: null,
        },
        {
          text: 'Roast the potatoes on their own.',
          why: 'Potatoes take the longest, so they get a head start. Staggering is how everything finishes together.',
          timerSeconds: 900,
        },
        {
          text: 'While they roast, cut the broccoli, pepper and onion into pieces about the size of the potato halves, and slice the sausage. Toss it all in the bowl with the remaining oil, the remaining salt and the pepper.',
          why: 'Pieces the same size cook at the same rate.',
          timerSeconds: null,
        },
        {
          text: 'Add everything to the pan and spread it into a single layer with a little space between pieces.',
          why: 'Crowded food traps steam and turns soft. If it does not fit in one layer, use a second pan.',
          timerSeconds: null,
        },
        {
          text: 'Roast, stirring once halfway, until a fork slides easily into a potato and the edges of the vegetables are browned.',
          why: 'The sausage is already cooked, so you are only browning it. Judging raw meat comes later, with a thermometer.',
          timerSeconds: 1200,
        },
        {
          text: 'Taste a potato and a piece of broccoli. Add a pinch of salt if they need it.',
          why: null,
          timerSeconds: null,
        },
      ],
      delivery: { label: 'Sausage and roasted vegetable plate', menuPriceCents: 1500 },
      pairing: {
        wine: 'Côtes du Rhône',
        principle: 'Match weight with weight',
        why: 'Smoky sausage and roasted vegetables are medium-heavy food. A medium-bodied, fruity red stands up to them without taking over.',
      },
    },
  },

  // ───────────────────────── Second course ─────────────────────────
  {
    id: 'marinara-pasta',
    title: 'Pasta with quick marinara',
    tier: 2,
    track: 'pizza-pasta',
    blurb: 'Your first real sauce. Later it becomes your pizza sauce.',
    teaches: ['sweating-aromatics', 'simmering'],
    requires: ['boiling-pasta', 'knife-basics'],
    content: {
      servings: 4,
      activeMinutes: 25,
      totalMinutes: 50,
      equipment: [
        'Large pot with lid',
        'Medium saucepan, about 3 quarts',
        'Wooden spoon',
        'Tongs',
        'Colander',
        'Mug',
        'Can opener',
        'Chef’s knife',
        'Cutting board',
        'Grater',
        'Measuring spoons',
      ],
      ingredients: [
        { ingredientId: 'yellow-onion', qty: 1, prep: 'finely chopped' },
        { ingredientId: 'garlic', qty: 4, prep: 'thinly sliced' },
        { ingredientId: 'olive-oil', qty: 3, prep: null },
        { ingredientId: 'red-pepper-flakes', qty: 0.25, prep: null },
        { ingredientId: 'crushed-tomatoes', qty: 28, prep: null },
        { ingredientId: 'butter', qty: 2, prep: null },
        { ingredientId: 'spaghetti', qty: 16, prep: null },
        { ingredientId: 'parmesan', qty: 1, prep: 'finely grated, to serve' },
        { ingredientId: 'kosher-salt', qty: 7, prep: '1 for the sauce, 6 for the pasta water' },
      ],
      steps: [
        {
          text: 'Cut the onion in half through the root, the hairy end, and peel off the papery skin. Lay each half flat side down. Slice it thin from end to end, stopping short of the root, then slice across to make pieces about the size of a pea. Slice the garlic thin.',
          why: 'The uncut root holds the layers together while you slice. Small pieces melt into the sauce; big ones stay crunchy.',
          timerSeconds: null,
        },
        {
          text: 'Put the oil, the onion and ½ teaspoon of the salt in the saucepan over medium heat. Cook, stirring every minute or so with the wooden spoon, until the onion is soft, see-through and only just golden at the edges, about 8 minutes.',
          why: 'This is sweating: gentle heat that softens the onion and brings out its sweetness without browning it. The salt pulls water out of the onion so it softens faster. If it starts to brown, turn the heat down.',
          timerSeconds: null,
        },
        {
          text: 'Add the garlic and pepper flakes and stir for 1 minute, until the garlic smells sweet and strong. Do not let it brown.',
          why: 'Garlic burns much faster than onion, so it goes in last and stays only a minute.',
          timerSeconds: null,
        },
        {
          text: 'Pour in the tomatoes and add ½ teaspoon of the salt. Turn the heat to medium-high until the sauce bubbles, then turn it down to low.',
          why: 'Cold tomatoes stop the cooking. Bring them up to a bubble first, then turn the heat down to hold a simmer.',
          timerSeconds: null,
        },
        {
          text: 'Simmer uncovered, stirring every 5 minutes and scraping the bottom. You want a slow bubble here and there, not a boil. It is fine to let it go longer than the timer while the pasta cooks.',
          why: 'Simmering cooks off water, so the sauce thickens and tastes deeper. A hard boil scorches the bottom and spits. If it spits, turn the heat down.',
          timerSeconds: 1200,
        },
        {
          text: 'While the sauce simmers, fill the large pot with 4 quarts of water, cover it, and bring it to a rolling boil over high heat: big bubbles that keep coming even when you stir. It takes about 15 minutes. Grate the parmesan while you wait.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'Add 2 tablespoons of salt to the boiling water, which is the 6 teaspoons left in the list, then the spaghetti. Stir for the first 30 seconds. Cook it 1 minute less than the box says. The timer is set for a 10-minute box.',
          why: 'The pasta finishes in the sauce for a minute, so it comes out of the water just short of done.',
          timerSeconds: 540,
        },
        {
          text: 'Dip the mug into the pot and fill it with pasta water. Then drain the spaghetti in the colander.',
          why: 'The starchy water helps the sauce cling to every strand.',
          timerSeconds: null,
        },
        {
          text: 'Turn off the heat under the sauce. Put the spaghetti back in its pot over low heat with the butter, about three-quarters of the sauce and a splash of pasta water. Toss with the tongs for 1 minute, until every strand is coated and nothing pools in the bottom. Add more pasta water if it looks dry.',
          why: 'Butter softens the sharp edge of the tomatoes and makes the sauce glossy.',
          timerSeconds: null,
        },
        {
          text: 'Taste a strand. If it tastes flat, add a pinch of salt and toss again. Serve with the rest of the sauce spooned on top and the parmesan.',
          why: null,
          timerSeconds: null,
        },
      ],
      delivery: { label: 'Spaghetti marinara', menuPriceCents: 1400 },
      pairing: {
        wine: 'Chianti (Sangiovese)',
        principle: 'Tomato sauce needs a high-acid wine',
        why: 'Tomatoes are sharp. A soft, low-acid red tastes flabby and dull beside them. Sangiovese, the grape of Chianti, has the bright acid to keep up.',
      },
    },
  },
  {
    id: 'pasta-al-limone',
    title: 'Pasta al limone',
    tier: 2,
    track: 'pizza-pasta',
    blurb: 'Butter, lemon and pasta water become a sauce with nothing else holding them together.',
    teaches: ['pan-emulsion'],
    requires: ['boiling-pasta', 'mise-en-place'],
    content: {
      servings: 2,
      activeMinutes: 20,
      totalMinutes: 30,
      equipment: [
        'Large pot with lid',
        'Large skillet, 12 inch',
        'Tongs',
        'Grater',
        'Small bowl',
        'Mug',
        'Chef’s knife',
        'Cutting board',
        'Measuring spoons',
      ],
      ingredients: [
        { ingredientId: 'spaghetti', qty: 8, prep: null },
        { ingredientId: 'lemon', qty: 2, prep: 'both zested, one juiced' },
        { ingredientId: 'butter', qty: 4, prep: 'cut into 4 pieces, kept cold' },
        { ingredientId: 'parmesan', qty: 1.5, prep: 'finely grated' },
        { ingredientId: 'black-pepper', qty: 0.5, prep: null },
        { ingredientId: 'kosher-salt', qty: 4.5, prep: 'for the pasta water' },
      ],
      steps: [
        {
          text: 'Before any heat: grate the yellow skin off both lemons on the fine side of the grater, turning each lemon as you go and stopping when you see white. Cut one lemon in half across its middle and squeeze both halves into the small bowl through your fingers, which catch the seeds. Grate the parmesan as fine as you can. Cut the butter into 4 pieces and put it back in the fridge.',
          why: 'The yellow skin, called zest, holds the lemon’s perfume. The white underneath is bitter. The sauce comes together in two minutes, so everything has to be ready first.',
          timerSeconds: null,
        },
        {
          text: 'Fill the large pot with 3 quarts of water, cover, and bring to a rolling boil over high heat. Add 1½ tablespoons of salt, which is the 4½ teaspoons in the list.',
          why: 'Less water than usual, on purpose. The starch the pasta gives off is more concentrated, and starch is what holds this sauce together.',
          timerSeconds: null,
        },
        {
          text: 'Add the spaghetti and stir for the first 30 seconds. Cook it 2 minutes less than the box says. The timer is set for a 10-minute box.',
          why: 'It finishes cooking in the skillet, in the sauce.',
          timerSeconds: 480,
        },
        {
          text: 'While it boils, put 1 piece of the butter, all of the zest and the pepper in the skillet over low heat. When the butter has melted and the kitchen smells of lemon, about 1 minute, turn the heat off.',
          why: 'Warm butter pulls the flavor out of the zest.',
          timerSeconds: null,
        },
        {
          text: 'When the timer goes, fill the mug with pasta water. Then lift the spaghetti straight into the skillet with the tongs, letting it drip a little on the way. Leave the pot of water on the stove.',
          why: 'Wet pasta is fine here. The water that comes with it is part of the sauce.',
          timerSeconds: null,
        },
        {
          text: 'Turn the skillet to medium. Add half the mug of pasta water, the lemon juice and the remaining 3 pieces of butter. Toss and stir with the tongs, nonstop, until the butter melts and the liquid turns from watery to creamy and clings to the strands, about 2 minutes.',
          why: 'This is a pan emulsion. Butter and water will not mix on their own, but the starch from the pasta holds them together in a glossy sauce. Keep it moving the whole time.',
          timerSeconds: null,
        },
        {
          text: 'Take the skillet off the heat. Add the parmesan a handful at a time, tossing after each one. If the sauce turns thick or clumpy, add a splash of pasta water and toss again. It should flow like heavy cream.',
          why: 'Cheese over high heat seizes into rubbery clumps. Off the heat, it melts smoothly into the sauce.',
          timerSeconds: null,
        },
        {
          text: 'Taste. Add a pinch of salt if it is flat, or a squeeze of the second lemon if it is dull. Eat right away.',
          why: 'The sauce thickens as it cools. If it gets tight on the plate, a spoonful of hot pasta water loosens it.',
          timerSeconds: null,
        },
      ],
      delivery: { label: 'Lemon butter pasta', menuPriceCents: 1500 },
      pairing: {
        wine: 'Chablis (unoaked Chardonnay)',
        principle: 'Pair with the sauce, not the pasta',
        why: 'Pasta itself tastes of little; the butter and lemon are what the wine meets. Chablis has the body for the butter and the acid for the lemon.',
      },
    },
  },
  {
    id: 'seared-chicken-thighs',
    title: 'Seared chicken thighs with roasted broccoli',
    tier: 2,
    track: 'foundations',
    blurb: 'Your first raw meat, with a thermometer to take the guessing out of it.',
    teaches: ['searing', 'doneness'],
    requires: ['heat-control', 'seasoning', 'roasting'],
    content: {
      servings: 3,
      activeMinutes: 30,
      totalMinutes: 40,
      equipment: [
        'Rimmed sheet pan',
        'Large skillet, 12 inch',
        'Tongs',
        'Instant-read thermometer',
        'Two large plates',
        'Paper towels',
        'Chef’s knife',
        'Cutting board',
        'Measuring spoons',
      ],
      ingredients: [
        { ingredientId: 'chicken-thighs', qty: 1.5, prep: 'about 6 thighs' },
        { ingredientId: 'broccoli', qty: 2, prep: 'cut into florets' },
        { ingredientId: 'olive-oil', qty: 2, prep: null },
        { ingredientId: 'neutral-oil', qty: 1, prep: null },
        { ingredientId: 'kosher-salt', qty: 1.5, prep: '½ for the broccoli, 1 for the chicken' },
        { ingredientId: 'black-pepper', qty: 0.5, prep: null },
        { ingredientId: 'lemon', qty: 1, prep: 'cut lengthwise into 4 wedges' },
      ],
      steps: [
        {
          text: 'Put a rack in the middle of the oven and heat it to 425°F.',
          why: 'The broccoli roasts while you cook the chicken, so the oven goes on first.',
          timerSeconds: null,
        },
        {
          text: 'Cut the broccoli into florets, the little trees at the top, each about the size of a golf ball. Trim the tough skin off the thick stem with the knife and slice the stem into coins. On the sheet pan, toss everything with the olive oil and ½ teaspoon of the salt, and spread it out in one layer.',
          why: 'Cut vegetables before you touch raw chicken, so the board and knife are still clean for them. A peeled stem is as good as the tops.',
          timerSeconds: null,
        },
        {
          text: 'When the oven is hot, roast the broccoli until the edges are dark brown and crisp and the stems are tender. When the timer ends, take the pan out and set it on the stovetop.',
          why: 'It needs no attention while you cook the chicken. Dark edges are flavor, not burning.',
          timerSeconds: 1200,
        },
        {
          text: 'Set out two plates: one by the sink for the raw chicken, one by the stove for the cooked chicken. Open the chicken onto the raw plate and throw the package away. Do not rinse the chicken.',
          why: 'Raw chicken often carries salmonella. Rinsing does not remove it; it splashes it around the sink. Cooking to the right temperature is what makes chicken safe, and separate plates keep raw and cooked from touching.',
          timerSeconds: null,
        },
        {
          text: 'Pat each thigh dry on both sides with paper towels and throw the towels away. Unfold each thigh so it lies flat. Sprinkle both sides with the remaining 1 teaspoon of salt and the pepper. Then wash your hands with soap and warm water for 20 seconds.',
          why: 'A wet surface steams instead of browning; dry chicken sears. Wash your hands every time you touch raw meat, before you touch anything else.',
          timerSeconds: null,
        },
        {
          text: 'Put the skillet over medium-high heat and add the neutral oil. Wait until the oil shimmers, with faint ripples running across it, about 2 minutes.',
          why: 'Searing needs a hot pan. Shimmering oil is the sign it is ready.',
          timerSeconds: null,
        },
        {
          text: 'With the tongs, lay the thighs in the pan smooth side down (the rounder side, where the skin was), with space between them. They should sizzle loudly. If they will not all fit without touching, cook them in two batches. Then wash the tongs in hot, soapy water.',
          why: 'Crowded chicken traps steam and turns grey. The tongs have touched raw chicken, so they get washed before they touch cooked chicken.',
          timerSeconds: null,
        },
        {
          text: 'Leave the thighs alone for 5 to 6 minutes: no moving, no poking. Lift one corner with the tongs to peek. They are ready to flip when the underside is deep golden brown and lets go of the pan without tugging. If one sticks, give it another minute.',
          why: 'Meat sticks at first and lets go on its own once a crust forms. Pulling early tears the crust off. If the oil smokes heavily, turn the heat to medium.',
          timerSeconds: null,
        },
        {
          text: 'Flip each thigh and cook the second side until it is browned too, 4 to 6 minutes.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'Push the thermometer into the thickest part of the biggest thigh, from the side, without touching the pan. It must read at least 165°F. If it is lower, cook 2 more minutes and check again.',
          why: 'Chicken is safe at 165°F, and the color inside can fool you. Thighs have more fat than breasts, so they stay juicy up to 175°F and beyond. A little over is better than under.',
          timerSeconds: null,
        },
        {
          text: 'Move the chicken to the clean plate with the clean tongs and let it rest. Meanwhile, put the raw-chicken plate in hot, soapy water, wipe the counter where it sat, wash the thermometer probe, and wash your hands.',
          why: 'Resting lets the juices settle back into the meat. Cleaning up now means nothing raw is left out when you sit down to eat.',
          timerSeconds: 300,
        },
        {
          text: 'Squeeze lemon over the chicken and broccoli. Taste a piece of each and add a pinch of salt if it needs it.',
          why: null,
          timerSeconds: null,
        },
      ],
      delivery: { label: 'Grilled chicken plate with broccoli', menuPriceCents: 1700 },
      pairing: {
        wine: 'Pinot Noir',
        principle: 'Browned chicken can take a light red',
        why: 'Searing gives chicken deep, toasty flavors that a delicate white can miss. Pinot Noir is light, with soft tannin and bright fruit, so it meets the crust without burying the meat.',
      },
    },
  },
  {
    id: 'egg-fried-rice',
    title: 'Egg fried rice',
    tier: 2,
    track: 'wok-curry',
    blurb: 'Cold rice, a very hot pan, and no time to chop once you start.',
    teaches: ['stir-frying'],
    requires: ['steaming-rice', 'mise-en-place', 'knife-basics'],
    content: {
      servings: 2,
      activeMinutes: 25,
      totalMinutes: 65,
      equipment: [
        'Small saucepan with a tight lid',
        'Fine-mesh strainer',
        'Rimmed sheet pan',
        'Large skillet, 12 inch',
        'Spatula',
        'Medium bowl',
        'Small bowl',
        'Fork',
        'Chef’s knife',
        'Cutting board',
        'Measuring spoons',
      ],
      ingredients: [
        { ingredientId: 'jasmine-rice', qty: 1, prep: 'cooked and chilled in steps 1 and 2' },
        { ingredientId: 'eggs', qty: 3, prep: null },
        { ingredientId: 'scallion', qty: 4, prep: 'thinly sliced, white and green parts kept apart' },
        { ingredientId: 'frozen-peas-carrots', qty: 0.75, prep: 'straight from the freezer' },
        { ingredientId: 'garlic', qty: 2, prep: 'minced' },
        { ingredientId: 'neutral-oil', qty: 3, prep: null },
        { ingredientId: 'soy-sauce', qty: 1.5, prep: null },
        { ingredientId: 'sesame-oil', qty: 1, prep: null },
        { ingredientId: 'kosher-salt', qty: 0.25, prep: null },
      ],
      steps: [
        {
          text: 'Rinse the rice in the strainer until the water runs mostly clear. Put it in the saucepan with 1¼ cups of water and bring it to a boil over high heat. Stir once, cover, turn the heat to its lowest setting, and cook without lifting the lid.',
          why: 'The same rice you learned on the rice bowl. This time it gets chilled before it is fried.',
          timerSeconds: 900,
        },
        {
          text: 'Turn off the heat. Spread the hot rice in a thin layer on the sheet pan and put it in the fridge, uncovered.',
          why: 'Fried rice needs cold, dry rice. Fresh rice is soft and wet and turns to mush in a hot pan. Day-old rice from the fridge is even better: next time, cook it the day before and start at step 3.',
          timerSeconds: 1800,
        },
        {
          text: 'While the rice chills, slice the scallions thin, keeping the white and green parts in separate piles. Mince the garlic: slice it thin, then chop the slices until the pieces are tiny. Beat the eggs with the salt in the medium bowl. Stir the soy sauce and sesame oil together in the small bowl.',
          why: 'Once the pan is hot, everything happens in under 10 minutes. Line it all up by the stove in the order it goes in: eggs, scallion whites and garlic, rice, peas and carrots, sauce, scallion greens.',
          timerSeconds: null,
        },
        {
          text: 'Heat 1 tablespoon of the neutral oil in the skillet over medium-high until it shimmers. Pour in the eggs, wait 10 seconds, then push them around with the spatula into big, soft curds, about 1 minute. Tip them back into their bowl while they still look a little wet.',
          why: 'The eggs come out early so they stay tender. They finish cooking when they go back in at the end.',
          timerSeconds: null,
        },
        {
          text: 'Add the remaining 2 tablespoons of oil, then the scallion whites and garlic. Stir for 30 seconds, until they smell fragrant. Do not let the garlic brown.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'Add the cold rice and turn the heat to high, or keep it at medium-high if your skillet is nonstick. Break up the clumps with the spatula, spread the rice out, and leave it for 1 minute to toast. Stir, spread it out again, and repeat for 3 to 4 minutes, until the grains are hot and separate and a few are crisp.',
          why: 'This is stir-frying: high heat and small amounts, so food fries instead of steaming. Leaving it still lets it toast; stirring keeps it from burning. You should hear a steady crackle. Nonstick pans stay at medium-high because high heat damages the coating.',
          timerSeconds: null,
        },
        {
          text: 'Add the peas and carrots straight from the freezer and stir for 1 minute, until they are hot.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'Pour the soy sauce mixture around the edge of the pan, add the eggs back, and toss for 30 seconds, breaking the eggs into pieces. Take the pan off the heat and stir in the scallion greens. Taste, and add a few drops of soy sauce if it needs salt.',
          why: 'Sauce poured on the hot edge of the pan sizzles and toasts on its way in.',
          timerSeconds: null,
        },
      ],
      delivery: { label: 'Egg fried rice', menuPriceCents: 1200 },
      pairing: {
        wine: 'Alsace Pinot Gris',
        principle: 'Aromatic food, aromatic wine',
        why: 'Sesame, scallion and soy are strong smells. A fragrant, fuller white holds its own beside them, where a neutral one would vanish.',
      },
    },
  },
  {
    id: 'onion-melt',
    title: 'Caramelized onion melt',
    tier: 2,
    track: 'burgers-sandwiches',
    blurb: 'Grilled cheese with onions you cooked for forty patient minutes.',
    teaches: ['caramelizing'],
    requires: ['griddling', 'knife-basics'],
    content: {
      servings: 2,
      activeMinutes: 25,
      totalMinutes: 65,
      equipment: [
        'Large skillet, 12 inch',
        'Lid or plate that covers the skillet',
        'Spatula',
        'Tongs',
        'Medium bowl',
        'Butter knife',
        'Chef’s knife',
        'Cutting board',
        'Measuring spoons',
      ],
      ingredients: [
        { ingredientId: 'yellow-onion', qty: 3, prep: 'thinly sliced' },
        { ingredientId: 'butter', qty: 4, prep: '2 for the onions, 2 softened for the bread' },
        { ingredientId: 'olive-oil', qty: 1, prep: null },
        { ingredientId: 'kosher-salt', qty: 0.5, prep: null },
        { ingredientId: 'sandwich-bread', qty: 4, prep: null },
        { ingredientId: 'cheddar', qty: 4, prep: 'sliced thin or grated' },
      ],
      steps: [
        {
          text: 'Cut each onion in half through the root and peel it. Lay the halves flat side down and slice them about as thin as a coin, cutting from the root end to the tip.',
          why: 'That is a lot of onion. It cooks down to about a quarter of the pile. Slices cut from root to tip hold their shape instead of turning to mush.',
          timerSeconds: null,
        },
        {
          text: 'Put 2 tablespoons of the butter and the olive oil in the skillet over medium heat. When the butter foams, add the onions and the salt and turn them with the spatula until they are coated.',
          why: 'The oil keeps the butter from burning over a long cook.',
          timerSeconds: null,
        },
        {
          text: 'Cook, stirring every 2 to 3 minutes, until the onions are limp, have given off their water and have shrunk by about half, about 10 minutes.',
          why: 'The salt draws water out of the onions. Softening comes first; browning only starts once the water is gone.',
          timerSeconds: null,
        },
        {
          text: 'Turn the heat to medium-low. Keep cooking, stirring every 3 to 5 minutes, for 30 to 40 minutes more, until the onions are deep amber brown, soft as jam and smell sweet. Whenever a brown film builds up on the pan, add 2 tablespoons of water and scrape it loose.',
          why: 'Caramelizing is the onion’s own sugar browning, slowly. Too hot and the outside burns before the inside sweetens. The brown film is flavor; the water lifts it back into the onions. If the edges start to blacken, turn the heat down and add water.',
          timerSeconds: null,
        },
        {
          text: 'Taste a strand. It should be sweet and savory; add a pinch of salt if it is flat. Scrape the onions into the bowl, take the skillet off the heat, and wipe it out with a paper towel held in the tongs.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'Spread the remaining 2 tablespoons of butter over one side of each slice of bread, all the way to the edges.',
          why: 'Same as grilled cheese: edge-to-edge butter, edge-to-edge browning.',
          timerSeconds: null,
        },
        {
          text: 'Build each sandwich on the board: a slice of bread butter side down, a quarter of the cheese, half the onions, another quarter of the cheese, and a second slice butter side up.',
          why: 'Cheese on both sides glues the onions in.',
          timerSeconds: null,
        },
        {
          text: 'Put the sandwiches in the skillet and set it over medium-low heat. Cook until the bottoms are deep golden brown. Lift a corner to check.',
          why: null,
          timerSeconds: 240,
        },
        {
          text: 'Flip both sandwiches, cover the skillet, and cook until the second side is golden and the cheese has melted.',
          why: 'The lid traps heat to melt the cheese through the thicker filling.',
          timerSeconds: 240,
        },
        {
          text: 'Rest the sandwiches on the board, then cut them in half.',
          why: null,
          timerSeconds: 60,
        },
      ],
      delivery: { label: 'Grilled cheese with caramelized onions', menuPriceCents: 1300 },
      pairing: {
        wine: 'Vouvray demi-sec (Chenin Blanc)',
        principle: 'Sweet flavors want a touch of sweetness in the glass',
        why: 'Slow-cooked onions taste sweet, and sweet food makes a bone-dry wine taste thin and sour. A Vouvray with a little sweetness keeps up, and its acid cuts the melted cheese.',
      },
    },
  },
  {
    id: 'red-lentil-dal',
    title: 'Red lentil dal with rice',
    tier: 2,
    track: 'wok-curry',
    blurb: 'A pot of lentils finished with spices sizzled in hot oil.',
    teaches: ['blooming-spices'],
    requires: ['steaming-rice', 'sweating-aromatics'],
    content: {
      servings: 2,
      activeMinutes: 25,
      totalMinutes: 45,
      equipment: [
        'Small saucepan with a tight lid',
        'Medium saucepan with lid',
        'Fine-mesh strainer',
        'Nonstick skillet, 8 to 10 inch',
        'Wooden spoon',
        'Grater',
        'Spoon',
        'Fork',
        'Chef’s knife',
        'Cutting board',
        'Measuring cups',
        'Measuring spoons',
      ],
      ingredients: [
        { ingredientId: 'red-lentils', qty: 0.75, prep: null },
        { ingredientId: 'jasmine-rice', qty: 1, prep: null },
        { ingredientId: 'yellow-onion', qty: 1, prep: 'finely chopped' },
        { ingredientId: 'garlic', qty: 3, prep: 'minced' },
        { ingredientId: 'ginger', qty: 1, prep: 'peeled; about a 1-inch piece' },
        { ingredientId: 'turmeric', qty: 0.5, prep: null },
        { ingredientId: 'cumin-seeds', qty: 1, prep: null },
        { ingredientId: 'red-pepper-flakes', qty: 0.25, prep: null },
        { ingredientId: 'neutral-oil', qty: 1, prep: null },
        { ingredientId: 'butter', qty: 2, prep: null },
        { ingredientId: 'kosher-salt', qty: 1.25, prep: null },
        { ingredientId: 'lemon', qty: 0.5, prep: null },
      ],
      steps: [
        {
          text: 'Start the rice: rinse it in the strainer, then bring it to a boil with 1¼ cups of water in the small saucepan over high heat. Stir once, cover, turn the heat to its lowest setting, and cook without lifting the lid. When the timer ends, turn the heat off and leave the lid on until you serve.',
          why: 'Rice stays hot under its lid for half an hour, so it can be ready first.',
          timerSeconds: 900,
        },
        {
          text: 'Rinse the lentils in the strainer under cold water, swishing them with your hand, until the water runs mostly clear. Pick out any tiny stones.',
          why: 'Rinsing washes off dust and the loose starch that foams up in the pot.',
          timerSeconds: null,
        },
        {
          text: 'Finely chop the onion and mince the garlic. Scrape the skin off the ginger with the edge of a spoon, then grate 1 tablespoon on the fine side of the grater.',
          why: 'A spoon peels ginger’s knobbly skin with less waste than a knife.',
          timerSeconds: null,
        },
        {
          text: 'Put the oil, the onion and ¼ teaspoon of the salt in the medium saucepan over medium heat. Cook, stirring often, until the onion is soft and see-through but not brown, about 6 minutes.',
          why: 'Sweating, as in the marinara. The softened onion is the sweet base the lentils cook in.',
          timerSeconds: null,
        },
        {
          text: 'Add the garlic, ginger and turmeric and stir for 1 minute, until they smell fragrant.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'Add the lentils and 2½ cups of water. Bring to a boil over high heat, then turn the heat to low and set the lid on slightly open. Simmer, stirring every 5 minutes, until the lentils have fallen apart into a thick, creamy soup. If it gets thicker than oatmeal, stir in ¼ cup of water.',
          why: 'Red lentils have no skins, so they collapse on their own and need no blender. Skim off any foam that rises at the start with a spoon.',
          timerSeconds: 1200,
        },
        {
          text: 'Stir in the remaining 1 teaspoon of salt, turn the heat off, and cover the pot.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'Now the tadka, the sizzling finish. Melt the butter in the small skillet over medium heat. When it foams, add the cumin seeds. Within 20 to 30 seconds they will sizzle, turn a shade darker and smell toasty. Add the pepper flakes, swirl for 5 seconds, and pour everything straight into the dal.',
          why: 'The flavor in spices dissolves in fat, not water. A few seconds in hot butter blooms them, and the butter carries that flavor through the whole pot. Seconds matter: if the seeds turn black and smell bitter, wipe out the pan and start the tadka again.',
          timerSeconds: null,
        },
        {
          text: 'Stir the dal, squeeze in the juice of the half lemon, and taste. Add a pinch of salt or more lemon until it tastes bright. Fluff the rice with the fork and serve the dal over it.',
          why: null,
          timerSeconds: null,
        },
      ],
      delivery: { label: 'Dal tadka with rice', menuPriceCents: 1500 },
      pairing: {
        wine: 'Grüner Veltliner',
        principle: 'Echo a flavor in the dish',
        why: 'Grüner Veltliner has a peppery, earthy note of its own, so it echoes the cumin instead of fighting it, and its acid lifts the creamy lentils.',
      },
    },
  },

  // ───────────────────────── Third course ─────────────────────────
  {
    id: 'chicken-pan-sauce',
    title: 'Chicken with lemon pan sauce',
    tier: 3,
    track: 'foundations',
    blurb: 'The brown bits stuck to the pan are the sauce. Learn to get them back.',
    teaches: ['pan-sauce'],
    requires: ['searing', 'doneness'],
    content: {
      servings: 3,
      activeMinutes: 35,
      totalMinutes: 50,
      equipment: [
        'Rimmed sheet pan',
        'Large skillet, 12 inch, stainless steel or cast iron',
        'Tongs',
        'Instant-read thermometer',
        'Wooden spoon',
        'Heatproof bowl',
        'Two large plates',
        'Paper towels',
        'Small bowl',
        'Mug',
        'Chef’s knife',
        'Cutting board',
        'Measuring cups',
        'Measuring spoons',
      ],
      ingredients: [
        { ingredientId: 'chicken-thighs', qty: 1.5, prep: 'about 6 thighs' },
        { ingredientId: 'baby-potatoes', qty: 1.5, prep: 'halved' },
        { ingredientId: 'olive-oil', qty: 1, prep: null },
        { ingredientId: 'neutral-oil', qty: 1, prep: null },
        { ingredientId: 'garlic', qty: 2, prep: 'minced' },
        { ingredientId: 'chicken-broth', qty: 0.75, prep: null },
        { ingredientId: 'lemon', qty: 1, prep: 'juiced' },
        { ingredientId: 'dijon-mustard', qty: 1, prep: null },
        { ingredientId: 'butter', qty: 2, prep: 'cold, cut in two' },
        { ingredientId: 'parsley', qty: 0.25, prep: 'leaves chopped' },
        { ingredientId: 'kosher-salt', qty: 1.5, prep: '½ for the potatoes, 1 for the chicken' },
        { ingredientId: 'black-pepper', qty: 0.5, prep: null },
      ],
      steps: [
        {
          text: 'Put a rack in the middle of the oven and heat it to 425°F.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'Halve the potatoes. On the sheet pan, toss them with the olive oil and ½ teaspoon of the salt and turn each one cut side down. When the oven is hot, roast them. When the timer ends, a fork should slide in easily and the cut sides should be deep golden. If not, give them 5 more minutes.',
          why: 'The potatoes take the longest, so they go in before you start the chicken.',
          timerSeconds: 1800,
        },
        {
          text: 'Before you touch the chicken, get the sauce ready: mince the garlic, chop the parsley leaves, juice the lemon into the small bowl, measure the broth into the mug, and cut the cold butter in two. Keep the butter in the fridge.',
          why: 'A pan sauce takes 4 minutes from start to finish. There is no time to chop once it starts.',
          timerSeconds: null,
        },
        {
          text: 'Set a plate for the raw chicken by the sink and a clean plate by the stove. Open the chicken onto the raw plate, throw the package away, and do not rinse the chicken.',
          why: 'The same routine as the seared thighs, every time. Raw and cooked never share a plate.',
          timerSeconds: null,
        },
        {
          text: 'Pat each thigh dry with paper towels, unfold it flat, and season both sides with 1 teaspoon of the salt and the pepper. Throw the towels away and wash your hands with soap for 20 seconds.',
          why: 'Dry for a crust, and clean hands before you touch anything else.',
          timerSeconds: null,
        },
        {
          text: 'Heat the neutral oil in the skillet over medium-high until it shimmers. Lay the thighs in smooth side down with the tongs, with space between them, then wash the tongs in hot, soapy water.',
          why: 'Use stainless steel or cast iron for this one. The brown bits that stick to the pan become the sauce, and a nonstick pan barely makes any.',
          timerSeconds: null,
        },
        {
          text: 'Sear without moving the thighs until the undersides are deep brown and let go of the pan easily, 5 to 6 minutes. Flip them and cook 4 to 6 minutes more.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'Check the thickest thigh with the thermometer: it must read at least 165°F. If it is lower, cook 2 more minutes and check again. Move the chicken to the clean plate with the clean tongs, and wash the probe.',
          why: 'Thermometer, not color. Every time.',
          timerSeconds: null,
        },
        {
          text: 'Look at the bottom of the pan. Those brown stuck-on bits are called fond, and they are the flavor of your sauce. Turn the heat to medium. Tilt the pan and spoon off all but a thin film of fat into the heatproof bowl.',
          why: 'If the bits are black instead of brown, the sauce will taste burnt; next time, turn the heat down a little sooner. Never pour fat down the sink, where it hardens and clogs the pipe. Let it cool, then throw it in the trash.',
          timerSeconds: null,
        },
        {
          text: 'Add the garlic and stir for 30 seconds, until fragrant.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'Pour in the broth. It will hiss and steam. Scrape the bottom of the pan with the wooden spoon until every brown bit has dissolved into the liquid.',
          why: 'This is deglazing: liquid lifts the fond off the pan and into the sauce.',
          timerSeconds: null,
        },
        {
          text: 'Let it bubble hard until it has cooked down to about half, 2 to 3 minutes. Stir in the lemon juice, the mustard and any juices that have collected on the chicken plate.',
          why: 'Reducing concentrates the flavor and thickens the sauce. The mustard helps the butter blend in smoothly in the next step.',
          timerSeconds: null,
        },
        {
          text: 'Take the pan off the heat. Add the cold butter one piece at a time, swirling the pan until each piece melts into a glossy sauce. Stir in the parsley, taste, and add a pinch of salt if it needs it.',
          why: 'Cold butter swirled in off the heat thickens the sauce and makes it shine. Over the heat it would melt into a greasy layer instead.',
          timerSeconds: null,
        },
        {
          text: 'Spoon the sauce over the chicken and potatoes. Then put the raw-chicken plate in hot, soapy water, wipe the counter where it sat, and wash your hands.',
          why: null,
          timerSeconds: null,
        },
      ],
      delivery: { label: 'Lemon chicken with roasted potatoes', menuPriceCents: 1900 },
      pairing: {
        wine: 'Albariño',
        principle: 'Match the loudest flavor on the plate',
        why: 'The lemon is louder than the chicken. Albariño tastes of citrus and has the acid to stand next to a lemon sauce without tasting flat.',
      },
    },
  },
  {
    id: 'smash-cheeseburger',
    title: 'Single smash cheeseburger',
    tier: 3,
    track: 'burgers-sandwiches',
    blurb: 'One patty, one slice of cheese, one toasted bun. All of it is about the crust.',
    teaches: ['smash-crust'],
    requires: ['searing', 'griddling'],
    content: {
      servings: 2,
      activeMinutes: 30,
      totalMinutes: 30,
      equipment: [
        'Large skillet, 12 inch, stainless steel or cast iron',
        'Stiff metal spatula',
        'Parchment paper',
        'Instant-read thermometer',
        'Two large plates',
        'Butter knife',
        'Chef’s knife',
        'Cutting board',
        'Measuring spoons',
      ],
      ingredients: [
        { ingredientId: 'ground-beef', qty: 1, prep: 'cold from the fridge; makes 4 burgers' },
        { ingredientId: 'american-cheese', qty: 4, prep: null },
        { ingredientId: 'burger-buns', qty: 4, prep: null },
        { ingredientId: 'butter', qty: 2, prep: 'softened' },
        { ingredientId: 'yellow-onion', qty: 0.25, prep: 'sliced paper-thin' },
        { ingredientId: 'dill-pickles', qty: 12, prep: null },
        { ingredientId: 'ketchup', qty: 4, prep: null },
        { ingredientId: 'kosher-salt', qty: 1, prep: null },
        { ingredientId: 'black-pepper', qty: 0.5, prep: null },
      ],
      steps: [
        {
          text: 'Get the toppings ready first. Slice the quarter onion as thin as you can. Set out the pickles and ketchup. Open the buns and spread the butter on the cut sides. Tear 4 squares of parchment paper, about 6 inches across.',
          why: 'Each burger cooks in about 3 minutes. Once the beef is in the pan there is no time for anything else.',
          timerSeconds: null,
        },
        {
          text: 'Put the skillet over medium heat and toast the buns cut side down until golden, 1 to 2 minutes, in batches if they do not all fit. Set them on a plate cut side up.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'Divide the beef into 4 equal pieces and roll each one gently into a loose ball, a little smaller than a tennis ball. Do not pack or knead it. Put the balls on the second plate and back in the fridge. Wash your hands with soap for 20 seconds.',
          why: 'Loose meat makes a tender burger with lacy, crisp edges; packed meat turns dense. Cold meat sticks less to the paper and stays juicier.',
          timerSeconds: null,
        },
        {
          text: 'Turn on the stove fan and open a window. Turn the burner to high and heat the skillet for 3 to 4 minutes, until a drop of water skitters across it and vanishes in a second.',
          why: 'The crust needs a very hot pan, and it will smoke. Never use a nonstick pan for this: high heat ruins the coating.',
          timerSeconds: null,
        },
        {
          text: 'Put 2 beef balls in the pan, well apart. Lay a parchment square on one and press straight down hard with the spatula, pushing on the blade with your other hand, until the patty is about ¼ inch thick. Peel off the paper. Smash the second one the same way. Sprinkle each with ¼ teaspoon of the salt and a pinch of the pepper.',
          why: 'Smash in the first 30 seconds, while the beef is still cold and soft. After that, never press again: it only squeezes out the juice.',
          timerSeconds: null,
        },
        {
          text: 'Leave them alone for 2 to 2½ minutes, until the edges are deep brown and lacy and the tops have mostly turned from red to grey. Wash your hands while they cook.',
          why: 'Your hands touched raw beef when you put the balls in the pan.',
          timerSeconds: null,
        },
        {
          text: 'Slide the spatula under each patty, scraping hard against the pan so the crust comes up with the meat, and flip it. Lay a slice of cheese on each right away. Cook about 1 minute more, until the cheese melts.',
          why: 'The crust is the whole point. A firm scrape keeps it on the burger instead of the pan.',
          timerSeconds: null,
        },
        {
          text: 'Slide the thermometer into one patty from the side, to the center. It must read at least 160°F. If it is lower, cook 30 seconds more and check again. Then move both patties onto bottom buns.',
          why: 'Grinding spreads any germs from the surface of the beef all the way through, so ground beef needs to be cooked through, unlike a steak. A thin smash patty gets there fast.',
          timerSeconds: null,
        },
        {
          text: 'Scrape any burnt bits out of the pan, then cook the other 2 balls the same way: smash, season, wash your hands, 2 minutes, scrape, flip, cheese, check.',
          why: 'If the pan is smoking hard, turn the heat to medium-high for this batch.',
          timerSeconds: null,
        },
        {
          text: 'Top each burger with onion, 3 pickle chips and a tablespoon of ketchup on the top bun, and close it. Then wash the raw-beef plate, the spatula and the thermometer probe in hot, soapy water.',
          why: null,
          timerSeconds: null,
        },
      ],
      delivery: { label: 'Double cheeseburger', menuPriceCents: 1350 },
      pairing: {
        wine: 'Zinfandel',
        principle: 'Char and fat want ripe fruit',
        why: 'Crust, beef fat and sweet ketchup are loud flavors. A ripe, jammy Zinfandel matches the char and the sweetness, where a delicate wine would disappear.',
      },
    },
  },
  {
    id: 'weeknight-meat-sauce',
    title: 'Weeknight meat sauce',
    tier: 3,
    track: 'pizza-pasta',
    blurb: 'Marinara with browned beef. The short version of the ragù you are working toward.',
    teaches: ['browning-meat'],
    requires: ['simmering', 'sweating-aromatics', 'boiling-pasta'],
    content: {
      servings: 4,
      activeMinutes: 35,
      totalMinutes: 55,
      equipment: [
        'Large skillet, 12 inch',
        'Large pot with lid',
        'Spatula',
        'Instant-read thermometer',
        'Heatproof bowl',
        'Tongs',
        'Colander',
        'Mug',
        'Can opener',
        'Chef’s knife',
        'Cutting board',
        'Grater',
        'Measuring spoons',
      ],
      ingredients: [
        { ingredientId: 'ground-beef', qty: 1, prep: null },
        { ingredientId: 'yellow-onion', qty: 1, prep: 'finely chopped' },
        { ingredientId: 'garlic', qty: 4, prep: 'thinly sliced' },
        { ingredientId: 'tomato-paste', qty: 2, prep: null },
        { ingredientId: 'crushed-tomatoes', qty: 28, prep: null },
        { ingredientId: 'olive-oil', qty: 1, prep: null },
        { ingredientId: 'red-pepper-flakes', qty: 0.25, prep: null },
        { ingredientId: 'black-pepper', qty: 0.5, prep: null },
        { ingredientId: 'spaghetti', qty: 16, prep: null },
        { ingredientId: 'parmesan', qty: 2, prep: 'finely grated, to serve' },
        { ingredientId: 'kosher-salt', qty: 7.5, prep: '1 for the beef, ½ for the sauce, 6 for the pasta water' },
      ],
      steps: [
        {
          text: 'Before the meat comes out, finely chop the onion and slice the garlic thin.',
          why: 'Vegetables first, raw meat second, so nothing raw touches the vegetables.',
          timerSeconds: null,
        },
        {
          text: 'Heat the olive oil in the skillet over medium-high until it shimmers. Add the beef and press it into one flat layer across the whole pan with the spatula. Sprinkle it with 1 teaspoon of the salt and the black pepper. Throw the package away, wipe the counter where it sat with hot, soapy water, and wash your hands with soap for 20 seconds.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'Leave the beef alone until the underside is deep brown, 4 to 5 minutes. If liquid pools in the pan, keep going: it cooks off, and then the browning starts.',
          why: 'This is the whole skill. Stir ground beef right away and it steams in its own juice and turns grey. Undisturbed contact with a hot pan is what browns it, and brown means flavor.',
          timerSeconds: null,
        },
        {
          text: 'Break the beef into small pieces with the spatula and stir. Keep cooking, stirring now and then, until no pink is left, the liquid is gone and the meat sizzles, 4 to 5 minutes more. Push the thermometer into a pile of meat: it must read at least 160°F. Then wash the probe.',
          why: 'Ground beef is safe at 160°F, and color alone can fool you.',
          timerSeconds: null,
        },
        {
          text: 'Tilt the pan and push the meat uphill with the spatula. Spoon all but about 2 tablespoons of the fat into the heatproof bowl.',
          why: 'Never pour fat down the sink, where it hardens and clogs the pipe. Let it cool, then throw it in the trash.',
          timerSeconds: null,
        },
        {
          text: 'Turn the heat to medium. Add the onion and cook, stirring, until it is soft and see-through, 5 to 6 minutes. Its water will loosen the brown bits on the pan; scrape them up as you stir.',
          why: 'Sweating, as in the marinara, this time in beef fat.',
          timerSeconds: null,
        },
        {
          text: 'Add the garlic, the pepper flakes and the tomato paste. Stir constantly for 1 to 2 minutes, until the paste turns from bright red to a darker brick red.',
          why: 'Frying tomato paste cooks out its tinny taste and deepens it.',
          timerSeconds: null,
        },
        {
          text: 'Pour in the tomatoes, add ½ teaspoon of the salt, and scrape the bottom. Bring to a bubble, then turn the heat to low and simmer uncovered, stirring every 5 minutes. It is fine to let it go longer than the timer while the pasta cooks.',
          why: 'Twenty minutes of simmering is the short version of the three-hour ragù you are working toward.',
          timerSeconds: 1200,
        },
        {
          text: 'While it simmers, fill the large pot with 4 quarts of water, cover, and bring it to a rolling boil over high heat. Grate the parmesan while you wait.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'Add 2 tablespoons of salt to the boiling water, which is the 6 teaspoons left in the list, then the spaghetti. Stir for the first 30 seconds. Cook it 1 minute less than the box says. The timer is set for a 10-minute box.',
          why: null,
          timerSeconds: 540,
        },
        {
          text: 'Fill the mug with pasta water, then drain the spaghetti in the colander.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'Turn off the sauce. Put the spaghetti back in its pot over low heat with about two-thirds of the sauce and a splash of pasta water, and toss with the tongs for 1 minute until coated. Taste and add a pinch of salt if it needs it. Serve with the rest of the sauce on top and the parmesan.',
          why: null,
          timerSeconds: null,
        },
      ],
      delivery: { label: 'Spaghetti with meat sauce', menuPriceCents: 1700 },
      pairing: {
        wine: 'Montepulciano d’Abruzzo',
        principle: 'Fat softens a firm red',
        why: 'A sturdy red can feel rough on its own. Beef fat smooths out its grip, so it tastes better with this sauce than without it.',
      },
    },
  },
  {
    id: 'chicken-broccoli-stir-fry',
    title: 'Chicken and broccoli stir-fry',
    tier: 3,
    track: 'wok-curry',
    blurb: 'A takeout standard, and the sauce method behind most of the others.',
    teaches: ['stir-fry-sauce'],
    requires: ['stir-frying', 'steaming-rice', 'doneness'],
    content: {
      servings: 3,
      activeMinutes: 35,
      totalMinutes: 45,
      equipment: [
        'Medium saucepan with lid',
        'Fine-mesh strainer',
        'Large skillet, 12 inch',
        'Lid or plate that covers the skillet',
        'Spatula',
        'Instant-read thermometer',
        'Whisk or fork',
        'Large bowl',
        'Medium bowl',
        'Large plate',
        'Grater',
        'Chef’s knife',
        'Cutting board',
        'Measuring cups',
        'Measuring spoons',
      ],
      ingredients: [
        { ingredientId: 'chicken-thighs', qty: 1.5, prep: 'cut into 1-inch pieces' },
        { ingredientId: 'broccoli', qty: 2, prep: 'cut into bite-size florets' },
        { ingredientId: 'garlic', qty: 3, prep: 'minced' },
        { ingredientId: 'ginger', qty: 1, prep: 'peeled; about a 1-inch piece' },
        { ingredientId: 'scallion', qty: 2, prep: 'thinly sliced' },
        { ingredientId: 'neutral-oil', qty: 3, prep: null },
        { ingredientId: 'chicken-broth', qty: 0.5, prep: null },
        { ingredientId: 'soy-sauce', qty: 3, prep: null },
        { ingredientId: 'oyster-sauce', qty: 2, prep: null },
        { ingredientId: 'sugar', qty: 1, prep: null },
        { ingredientId: 'cornstarch', qty: 1, prep: null },
        { ingredientId: 'sesame-oil', qty: 1, prep: null },
        { ingredientId: 'kosher-salt', qty: 0.25, prep: null },
        { ingredientId: 'jasmine-rice', qty: 2, prep: 'makes extra for fried rice' },
      ],
      steps: [
        {
          text: 'Start the rice: rinse it in the strainer, then bring it to a boil with 2½ cups of water in the saucepan over high heat. Stir once, cover, turn the heat to its lowest setting, and cook without lifting the lid. When the timer ends, turn the heat off and leave the lid on.',
          why: 'This makes more than you need, on purpose. Leftover rice keeps 4 days in the fridge and is exactly what egg fried rice wants.',
          timerSeconds: 900,
        },
        {
          text: 'Make the sauce: in the medium bowl, whisk the broth, soy sauce, oyster sauce, sugar, cornstarch and sesame oil until no lumps of cornstarch are left.',
          why: 'Mixed ahead, the sauce goes in with one pour. The cornstarch is what thickens it in the pan.',
          timerSeconds: null,
        },
        {
          text: 'Cut the broccoli into bite-size florets and trim and slice the stem. Mince the garlic, peel and grate the ginger, and slice the scallions.',
          why: 'Vegetables before raw chicken, as always.',
          timerSeconds: null,
        },
        {
          text: 'Now the chicken: open it onto the cutting board, throw the package away, and cut the thighs into 1-inch pieces, trimming off any big pieces of fat. Put them in the large bowl and toss them with the salt. Then wash the board and the knife in hot, soapy water, and wash your hands with soap for 20 seconds.',
          why: 'Small, even pieces cook through in a few minutes.',
          timerSeconds: null,
        },
        {
          text: 'Heat 1 tablespoon of the neutral oil in the skillet over medium-high until it shimmers. Add the broccoli and 3 tablespoons of water and cover at once. Steam for 2 minutes, then uncover and stir until the water has cooked off and the broccoli is bright green and just tender, about 1 minute. Tip it onto a clean plate.',
          why: 'The water steams the thick stems through before the florets can burn.',
          timerSeconds: null,
        },
        {
          text: 'Add 1 tablespoon of oil and half the chicken in one layer. Leave it for 2 minutes to brown, then stir and cook until browned all over, 2 to 3 minutes more. Check the biggest piece with the thermometer: at least 165°F. Move this batch onto the broccoli.',
          why: 'Two batches, because a crowded pan steams chicken instead of browning it. Each batch is fully cooked before it touches the broccoli.',
          timerSeconds: null,
        },
        {
          text: 'Cook the rest of the chicken the same way with the last tablespoon of oil, and check the biggest piece again: at least 165°F. Leave it in the pan.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'Turn the heat to medium. Push the chicken to the sides, add the garlic and ginger to the middle, and stir them for 30 seconds until fragrant.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'Return the broccoli and the first batch of chicken to the pan. Stir the sauce again, since the cornstarch sinks, and pour it in. Stir constantly until it bubbles and turns thick and glossy, about 1 minute.',
          why: 'Cornstarch only thickens once it boils. If the sauce gets too thick, stir in a splash of water.',
          timerSeconds: null,
        },
        {
          text: 'Take the pan off the heat and scatter on the scallions. Taste a piece of broccoli with sauce on it, and add a few drops of soy sauce if it needs salt. Serve over the rice. Wash the bowl that held the raw chicken and the thermometer probe in hot, soapy water.',
          why: null,
          timerSeconds: null,
        },
      ],
      delivery: { label: 'Chicken and broccoli with white rice', menuPriceCents: 1600 },
      pairing: {
        wine: 'Dry rosé',
        principle: 'Rosé fits food that sits between red and white',
        why: 'A dark, savory sauce on white meat is halfway between a red wine dish and a white one. A dry rosé has a red’s fruit and a white’s freshness, so it fits both sides.',
      },
    },
  },
  {
    id: 'chana-masala',
    title: 'Chana masala',
    tier: 3,
    track: 'wok-curry',
    blurb: 'Chickpeas in the onion-tomato base that most North Indian curries start from.',
    teaches: ['masala-base'],
    requires: ['blooming-spices', 'simmering'],
    content: {
      servings: 4,
      activeMinutes: 35,
      totalMinutes: 55,
      equipment: [
        'Medium saucepan with lid',
        'Fine-mesh strainer',
        'Large skillet, 12 inch',
        'Wooden spoon',
        'Colander',
        'Can opener',
        'Small bowl',
        'Grater',
        'Spoon',
        'Fork',
        'Chef’s knife',
        'Cutting board',
        'Measuring cups',
        'Measuring spoons',
      ],
      ingredients: [
        { ingredientId: 'chickpeas', qty: 2, prep: 'drained and rinsed' },
        { ingredientId: 'crushed-tomatoes', qty: 14, prep: 'half a large can' },
        { ingredientId: 'yellow-onion', qty: 1, prep: 'finely chopped' },
        { ingredientId: 'garlic', qty: 4, prep: 'minced' },
        { ingredientId: 'ginger', qty: 1, prep: 'peeled; about a 1-inch piece' },
        { ingredientId: 'neutral-oil', qty: 3, prep: null },
        { ingredientId: 'cumin-seeds', qty: 1, prep: null },
        { ingredientId: 'coriander', qty: 2, prep: null },
        { ingredientId: 'garam-masala', qty: 1.5, prep: null },
        { ingredientId: 'turmeric', qty: 0.5, prep: null },
        { ingredientId: 'red-pepper-flakes', qty: 0.5, prep: null },
        { ingredientId: 'kosher-salt', qty: 1.5, prep: null },
        { ingredientId: 'lemon', qty: 0.5, prep: null },
        { ingredientId: 'jasmine-rice', qty: 2, prep: null },
      ],
      steps: [
        {
          text: 'Start the rice: rinse it in the strainer, then bring it to a boil with 2½ cups of water in the saucepan over high heat. Stir once, cover, turn the heat to its lowest setting, and cook without lifting the lid. When the timer ends, turn the heat off and leave the lid on.',
          why: 'Rice holds under its lid, so it can be ready first.',
          timerSeconds: 900,
        },
        {
          text: 'Finely chop the onion, mince the garlic, and peel and grate the ginger. Drain the chickpeas in the colander and rinse them. Measure the coriander, garam masala, turmeric and pepper flakes into the small bowl.',
          why: 'The ground spices go in together, so they share a bowl. The cumin seeds go in on their own, first.',
          timerSeconds: null,
        },
        {
          text: 'Heat the oil in the skillet over medium heat. Add the cumin seeds and let them sizzle for 20 to 30 seconds, until a shade darker and toasty-smelling.',
          why: 'Blooming, as in the dal: whole seeds in hot fat first.',
          timerSeconds: null,
        },
        {
          text: 'Add the onion and ½ teaspoon of the salt. Cook, stirring often, until the onion is soft and golden brown at the edges, 10 to 12 minutes. If it browns faster than that, turn the heat down.',
          why: 'This time you want color, more than sweating gives. Browned onion is the backbone of the masala.',
          timerSeconds: null,
        },
        {
          text: 'Add the garlic and ginger and stir for 1 minute.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'Add the bowl of ground spices and stir for 30 seconds. If they start to stick and darken fast, add a tablespoon of water.',
          why: 'Ground spices burn faster than whole seeds, so they get seconds, not minutes.',
          timerSeconds: null,
        },
        {
          text: 'Add the tomatoes and ½ teaspoon of the salt. Cook, stirring often and scraping the bottom, until the mixture thickens into a paste, turns deep brick red, and small pools of oil shine at its edges, 8 to 10 minutes.',
          why: 'This is the masala base. When the oil separates, the water has cooked off and the raw taste of the tomato and spices is gone. Rushing it leaves the curry sharp and thin.',
          timerSeconds: null,
        },
        {
          text: 'Add the chickpeas, 1 cup of water and the last ½ teaspoon of salt. Bring to a bubble, then turn the heat to low and simmer, stirring now and then. Halfway through, press a spoonful of chickpeas against the side of the pan to mash them.',
          why: 'The mashed chickpeas thicken the sauce.',
          timerSeconds: 900,
        },
        {
          text: 'Squeeze in the juice of the half lemon and taste. Add a pinch of salt if it is flat, or more pepper flakes if you want heat. Fluff the rice with the fork and serve the chana masala over it.',
          why: null,
          timerSeconds: null,
        },
      ],
      delivery: { label: 'Chana masala with rice', menuPriceCents: 1500 },
      pairing: {
        wine: 'Gewürztraminer',
        principle: 'Spice wants fruit, not oak or tannin',
        why: 'Warm spices and chili make oaky, tannic wines taste bitter and hot. A juicy, fragrant Gewürztraminer with a touch of sweetness cools them down instead.',
      },
    },
  },
  {
    id: 'oven-fries-aioli',
    title: 'Oven fries with garlic aioli',
    tier: 3,
    track: 'burgers-sandwiches',
    blurb: 'The side for every burger, with a sauce you whisk from an egg yolk and oil.',
    teaches: ['emulsions'],
    requires: ['roasting', 'knife-basics'],
    content: {
      servings: 2,
      activeMinutes: 30,
      totalMinutes: 55,
      equipment: [
        'Rimmed sheet pan',
        'Oven mitts',
        'Stiff metal spatula',
        'Large bowl',
        'Medium bowl',
        'Small bowl',
        'Whisk',
        'Kitchen towels',
        'Liquid measuring cup',
        'Grater',
        'Chef’s knife',
        'Cutting board',
        'Measuring spoons',
      ],
      ingredients: [
        { ingredientId: 'russet-potatoes', qty: 1.5, prep: 'scrubbed; about 2 large' },
        { ingredientId: 'neutral-oil', qty: 9, prep: '3 for the fries, 6 for the aioli' },
        { ingredientId: 'olive-oil', qty: 2, prep: null },
        { ingredientId: 'kosher-salt', qty: 1.25, prep: '1 for the fries, ¼ for the aioli' },
        { ingredientId: 'pasteurized-eggs', qty: 1, prep: 'yolk only' },
        { ingredientId: 'dijon-mustard', qty: 1, prep: null },
        { ingredientId: 'garlic', qty: 1, prep: 'finely grated' },
        { ingredientId: 'lemon', qty: 0.5, prep: 'juiced' },
      ],
      steps: [
        {
          text: 'Put a rack in the middle of the oven, set the sheet pan on it, and heat the oven to 450°F with the pan inside.',
          why: 'Fries that land on a hot pan start crisping at once and do not stick.',
          timerSeconds: null,
        },
        {
          text: 'Scrub the potatoes under running water and leave the skins on. Halve each one lengthwise, lay it flat side down, and cut it into ½-inch slabs. Lay the slabs flat and cut them into ½-inch sticks.',
          why: 'Flat side down, as always. Sticks the same size bake at the same rate.',
          timerSeconds: null,
        },
        {
          text: 'Put the sticks in the large bowl and cover them with hot tap water. Let them soak.',
          why: 'Soaking rinses off the loose starch on the surface, which makes fries gummy and sticky. Rinsed fries crisp.',
          timerSeconds: 600,
        },
        {
          text: 'Drain the fries and dry them very well: roll them up in a clean kitchen towel and rub. Dry the bowl too.',
          why: 'Water turns to steam in the oven, and steam makes soggy fries.',
          timerSeconds: null,
        },
        {
          text: 'Toss the fries in the dry bowl with 3 tablespoons of the neutral oil and 1 teaspoon of the salt.',
          why: null,
          timerSeconds: null,
        },
        {
          text: 'With oven mitts, take out the hot pan and spread the fries on it in one layer, not touching. They should sizzle. Roast them.',
          why: 'Space between the fries lets steam escape. If they will not fit, use a second pan.',
          timerSeconds: 1200,
        },
        {
          text: 'While they roast, make the aioli. Twist a damp kitchen towel into a ring on the counter and set the medium bowl in it so the bowl cannot spin.',
          why: 'You need one hand to whisk and one to pour.',
          timerSeconds: null,
        },
        {
          text: 'Separate the egg: crack it over the small bowl and pass the yolk back and forth between the half shells, letting the white drop into the bowl. Put the yolk in the medium bowl with the mustard, the garlic, ¼ teaspoon of the salt and 1 teaspoon of the lemon juice. Whisk for 10 seconds.',
          why: 'This is why the egg is pasteurized. The yolk stays raw in this sauce, and pasteurized eggs have been warmed just enough to kill salmonella while still acting like raw eggs. The white keeps covered in the fridge for 2 days.',
          timerSeconds: null,
        },
        {
          text: 'Mix the remaining 6 tablespoons of neutral oil and the olive oil in the measuring cup. Whisking nonstop, add the oil a few drops at a time. Once about 2 tablespoons are in and the sauce is thick and pale, pour the rest in a thread as thin as string, still whisking. It takes about 3 minutes.',
          why: 'This is an emulsion. The yolk coats tiny droplets of oil and keeps them apart, which is what makes the sauce thick. Add oil too fast and the droplets join up, and the sauce breaks into a greasy puddle.',
          timerSeconds: null,
        },
        {
          text: 'Taste, and whisk in more lemon juice or a pinch of salt until it tastes bright. If it ever turns thin and greasy, it has broken: whisk 1 teaspoon of mustard in a clean bowl, then whisk the broken sauce into it a few drops at a time until it thickens again.',
          why: 'Keep leftover aioli covered in the fridge and use it within 4 days.',
          timerSeconds: null,
        },
        {
          text: 'When the timer ends, flip the fries with the spatula and roast until they are deep golden and crisp.',
          why: 'Ovens differ. Check at the timer, and give them up to 5 more minutes if they are still pale.',
          timerSeconds: 600,
        },
        {
          text: 'Taste a fry and sprinkle on a pinch of salt if it needs it. Serve hot with the aioli.',
          why: null,
          timerSeconds: null,
        },
      ],
      delivery: { label: 'Fries with garlic aioli', menuPriceCents: 800 },
      pairing: {
        wine: 'Crémant or another dry sparkling wine',
        principle: 'Crisp food, crisp wine',
        why: 'Fries are salt, fat and crunch, and aioli adds more fat. Acid and bubbles scrub the fat off your tongue, so every fry tastes like the first.',
      },
    },
  },

  // ───────────────────────── Fourth course ─────────────────────────
  {
    id: 'pan-pizza',
    title: 'Cast-iron pan pizza',
    tier: 4,
    track: 'pizza-pasta',
    blurb: 'A forgiving dough that proofs in the same pan it bakes in.',
    teaches: ['yeasted-dough'],
    requires: ['simmering', 'roasting'],
    content: null,
  },
  {
    id: 'carbonara',
    title: 'Spaghetti carbonara',
    tier: 4,
    track: 'pizza-pasta',
    blurb: 'Eggs, cheese and pork fat, held just short of scrambling.',
    teaches: ['tempering-eggs'],
    requires: ['pan-emulsion', 'mise-en-place'],
    content: null,
  },
  {
    id: 'chicken-cutlets',
    title: 'Crispy chicken cutlets',
    tier: 4,
    track: 'burgers-sandwiches',
    blurb: 'Pounded thin, breaded, and fried in half an inch of oil.',
    teaches: ['breading-frying'],
    requires: ['searing', 'doneness'],
    content: null,
  },
  {
    id: 'thai-green-curry',
    title: 'Thai green curry with chicken',
    tier: 4,
    track: 'wok-curry',
    blurb: 'Store-bought paste, coconut milk, and the last-minute balancing that makes it taste like the restaurant’s.',
    teaches: ['curry-balance'],
    requires: ['stir-frying', 'steaming-rice', 'seasoning', 'doneness'],
    content: null,
  },
  {
    id: 'beef-and-broccoli',
    title: 'Beef and broccoli',
    tier: 4,
    track: 'wok-curry',
    blurb: 'The reason takeout beef is so tender, and how to do it at home.',
    teaches: ['velveting'],
    requires: ['stir-fry-sauce'],
    content: null,
  },
  {
    id: 'chicken-tikka',
    title: 'Broiled chicken tikka',
    tier: 4,
    track: 'wok-curry',
    blurb: 'Yogurt-marinated chicken charred under the broiler. Half of a tikka masala.',
    teaches: ['marinating-broiling'],
    requires: ['blooming-spices', 'doneness'],
    content: null,
  },

  // ───────────────────────── The usual ─────────────────────────
  {
    id: 'double-smash-burger',
    title: 'Double smash burger with oven fries',
    tier: 5,
    track: 'burgers-sandwiches',
    blurb: 'Two crusted patties, caramelized onions, your own burger sauce, fries on the side.',
    teaches: [],
    requires: ['smash-crust', 'caramelizing', 'emulsions'],
    content: null,
  },
  {
    id: 'crispy-chicken-sandwich',
    title: 'Crispy chicken sandwich',
    tier: 5,
    track: 'burgers-sandwiches',
    blurb: 'A fried cutlet on a toasted bun with pickles and spicy mayo.',
    teaches: [],
    requires: ['breading-frying', 'emulsions', 'griddling'],
    content: null,
  },
  {
    id: 'margherita-pizza',
    title: 'Margherita pizza',
    tier: 5,
    track: 'pizza-pasta',
    blurb: 'Hand-stretched dough, your own sauce, and the hottest oven you have.',
    teaches: [],
    requires: ['yeasted-dough', 'simmering'],
    content: null,
  },
  {
    id: 'ragu-bolognese',
    title: 'Tagliatelle with ragù bolognese',
    tier: 5,
    track: 'pizza-pasta',
    blurb: 'Three hours on the stove, most of them hands-off. The pasta order that travels worst and cooks best.',
    teaches: [],
    requires: ['browning-meat', 'pan-sauce', 'pan-emulsion'],
    content: null,
  },
  {
    id: 'pad-thai',
    title: 'Pad thai',
    tier: 5,
    track: 'wok-curry',
    blurb: 'Rice noodles, a sweet-sour-salty sauce, and four minutes of fast cooking.',
    teaches: [],
    requires: ['stir-fry-sauce', 'curry-balance', 'mise-en-place'],
    content: null,
  },
  {
    id: 'general-tsos-chicken',
    title: 'General Tso’s chicken',
    tier: 5,
    track: 'wok-curry',
    blurb: 'Crisp fried chicken in a glossy, sticky sauce, over your own rice.',
    teaches: [],
    requires: ['breading-frying', 'velveting', 'stir-fry-sauce', 'steaming-rice'],
    content: null,
  },
  {
    id: 'chicken-tikka-masala',
    title: 'Chicken tikka masala',
    tier: 5,
    track: 'wok-curry',
    blurb: 'Broiled tikka folded into a creamy masala. Two things you already know, combined.',
    teaches: [],
    requires: ['masala-base', 'marinating-broiling', 'steaming-rice'],
    content: null,
  },
]

export function recipeById(id: string): Recipe {
  const recipe = RECIPES.find((r) => r.id === id)
  if (!recipe) throw new Error(`Unknown recipe id: ${id}`)
  return recipe
}
